### ISSUE TITLE
Export option not showing up at all. 

### ISSUE THREAD

**Issue by DarkStarZN** [pionxzh/chatgpt-exporter#101]
![image](https://user-images.githubusercontent.com/74018454/229286955-7205ade5-1c62-4246-b6a1-858020c7fbfd.png)

As is shown in the screenshot, the Export feature does not appear at all, despite the script running.

**Comment by DarkStarZN** [comment]
Just to add, it is working fine in 2.4.1

**Comment by pionxzh** [comment]
Can you take a screenshot of the console error?
F12 - console

**Comment by pionxzh** [comment]
Ah never mind, I knew what happened.
