### ISSUE TITLE
24 hours option for HTML

### ISSUE THREAD

**Issue by kyoyacchi** [pionxzh/chatgpt-exporter#104]
Can you add 24 hours option for HTML?

**Comment by pionxzh** [comment]
? what is that?

**Comment by kyoyacchi** [comment]
> ? what is that?

![Screenshot_2023-04-04-16-12-01~2](https://user-images.githubusercontent.com/63583961/229802617-c2499733-536b-4ac7-98a0-83a224b32e07.png)

**Comment by kyoyacchi** [comment]
> I see, you mean this right? ![image](https://user-images.githubusercontent.com/9910706/229824077-12f8db3e-b0fb-4946-aa0a-ffef29eba35b.png)

Yes

**Comment by pionxzh** [comment]
![image](https://user-images.githubusercontent.com/9910706/230656452-3cf2d245-93f7-4627-b8d9-a0a1bba1ca86.png)

**Comment by kyoyacchi** [comment]
> ![image](https://user-images.githubusercontent.com/9910706/230656452-3cf2d245-93f7-4627-b8d9-a0a1bba1ca86.png)


![Screenshot_20230407-222631](https://user-images.githubusercontent.com/63583961/230665986-4aedd09f-de08-40c1-b45f-2c57e2717c3d.jpg)

**Comment by pionxzh** [comment]
![image](https://user-images.githubusercontent.com/9910706/230705246-9357c59f-0d3c-458f-a897-b5f51e9eb73e.png)
