### ISSUE TITLE
Feature: download and delete chat before closing tab

### ISSUE THREAD

**Issue by nullptrmachine** [pionxzh/chatgpt-exporter#105]
All I want is: on tab close make it wait until it downloads conversation into a file and deletes the conversation on a website, then close tab.

Could you please make this a feature? I'm sorry I cannot do it myself as I don't understand someone elses code but you do.

**Comment by pionxzh** [comment]
I will do #85 recently to provide the ability to delete multiple chats. Will that work for you? like export and clean chats once a week.

**Comment by pionxzh** [comment]
> They say conversations are private, but they loop through them to search for something that's the reason I don't want to keep my conversations on their server.

May I know who is "they"? OpenAI?
Then I will have to tell you: Don't send sensitive data to ChatGPT. The deletion is not real, it's more like saying "hey, hide this chat, so that it won't be that messy".
