### ISSUE TITLE
Cant mouse over exporter buttons

### ISSUE THREAD

**Issue by inventor2525** [pionxzh/chatgpt-exporter#111]
All the sudden when I move my mouse from export over to your panel, it immediately disappears and it renders under the ChatGPT replies. I have to scroll to mine to get it to show up.

I was on an older version just after you got #71 (thanks for that btw, very helpful!!) and it just started randomly, so I'm assuming it's on their end. (newes version still does it)

Suggest leaving the mouse over functionality, but adding the ability to press the export button to get the panel to lock and unlock open to minimize future issues like this. (obv after fixing any rendering order thing, but I could dig to the panel in the inspector if I had to if it just stayed open)

**Comment by pionxzh** [comment]
Do you still see this on v2.5.4? And can you specify which panel? We now have the "menu" / "setting" and "export all". 😆 
OpenAI has updated the page layout, which failed previous versions.

I will consider the clicking suggestion!

**Comment by inventor2525** [comment]
I moved to 2.5.4 before posting actually. -- Yes, I still see it. Re-booted browser after the switch too.

**Comment by pionxzh** [comment]
May I know your environment? Browser and OS.

**Comment by pionxzh** [comment]
After testing on the latest version of Firefox for Mac, it seems that I may have made the closing delay too short.
Did this occur randomly? I don't quite get it. sorry~

And could you please provide some screenshots to assist me in determining what occurred? Specifically, screenshots of the UI, console, and DOM structure that you mentioned as "rendering under the ChatGPT replies.". And this

**Comment by inventor2525** [comment]
It started randomly a few days ago without updating.

I then updated to see if it would fix it. -- It didn't

![Screenshot from 2023-04-05 13 02 53](https://user-images.githubusercontent.com/25239123/230152457-135bb9d4-06cb-4dda-9e68-b2e0b76809e0.png)

**Comment by inventor2525** [comment]
Probs... Be my luck.

If I scroll up it's visible on my prompts, so, if my prompt is long enough, your UI will be fully visible, but as you can see, my text overdraws it.

Then of course if ChatGPT's response is long enough and I scroll down, it's not visible at all. (as you can see it cuts off at the boundary of the 2.)

And that's reproducible on any conversation and any 2 comment/prompt pairs.

eg:
![Screenshot from 2023-04-05 15 10 26](https://user-images.githubusercontent.com/25239123/230181184-f4c95892-5ea9-49b0-b477-64372193bf3a.png)

**Comment by inventor2525** [comment]
Just a thought for now though... is there like a js method I could call to hit the json button? Maybe make a bookmarklet? :smile:

**Comment by inventor2525** [comment]
:face_palm:

............ And............. it's working now

When I said that I went into the inspector to just try moving your div up a bit or something to try and get to it.... and when that made things bad I re-loaded the page... and now it works.

**Comment by pionxzh** [comment]
There is no public method... Can you try other browsers first? If you really need the JSON file asap.

I have no idea what happened on your browser, especially it will be cut off by a response.

**Comment by pionxzh** [comment]
?_? what do you mean "working"? Everything is good now?

**Comment by inventor2525** [comment]
...yep...

idk? thing was dumb. -- I restarted the browser before too.

**Comment by pionxzh** [comment]
I think your script manager might somehow stuck on the old version. I have seen this on violetmonkey on Firefox before.

**Comment by pionxzh** [comment]
Ok... I think the script should print out the current version in the console so that it will be easier to debug.

**Comment by inventor2525** [comment]
possibly, idk ... it's working now though, so, not like I can re-produce. I guess just watch out for it if I was somehow being ab tested, or... maybe it was stuck on the old version, idk.

it's tampermonkey 4.18.1 if you wanna watch out for it or something though

**Comment by pionxzh** [comment]
The new version should be more compatible with different layouts. I'm closing this issue~
