### ISSUE TITLE
Extension does not work with ChatGPT Plus

### ISSUE THREAD

**Issue by patrickwitter** [pionxzh/chatgpt-exporter#116]
I recently updated my chatgpt tot the plus version and the export button disappeared

**Comment by pionxzh** [comment]
I'm also running on plus plan. Please provide the following information for me to trace what happened:
- Browser
- OS
- Script Version (Check in your script manager's dashboard)
- Error Message (Press F12, go to `console`, take a screenshot)

**Comment by peterkaminski** [comment]
Thank you so much for writing Exporter - it's so helpful!

I don't know if this is the same problem, but I have been using Exporter on the Plus plan for a week or two. I used it this morning and it worked fine. This afternoon the Export button has disappeared.

I have tried in both Chrome and Firefox, browsers are up-to-date.

I am running macOS 12.6.3.

I updated the script to 2.6.3.

I don't get any errors on the ChatGPT page.

On the script edit page in TamperMonkey, I get the error shown in this screenshot, in both browsers.

<img width="1327" alt="CleanShot 2023-04-13 at 12 35 02@2x" src="https://user-images.githubusercontent.com/169442/231865557-61b3c243-5820-4645-839a-d102cee929fb.png">

**Comment by patrickwitter** [comment]
> I'm also running on plus plan. Please provide the following information for me to trace what happened:
> 
> * Browser
> * OS
> * Script Version (Check in your script manager's dashboard)
> * Error Message (Press F12, go to `console`, take a "complete" screenshot)


My Browser is Chrome Version 111.0.5563.149 (Official Build) (64-bit)
OS is Windows 11 
Script version is 2.6.2
![Screenshot (104)](https://user-images.githubusercontent.com/53438425/231883916-784e3a8f-8fde-47b8-99e6-6576866939c3.png)

**Comment by pionxzh** [comment]
@peterkaminski ok, I might need you to refresh and monitor if there are any error messages in the console. I'm not sure if OpenAI is A/B testing you guys.

**Comment by pionxzh** [comment]
@patrickwitter Thanks. This is what I need. But can you scroll down to take another screenshot for all the error messages?

**Comment by patrickwitter** [comment]
It's the same error repeated down @pionxzh

**Comment by patrickwitter** [comment]
Getting fewer errors now, but now a different one 
![Screenshot (105)](https://user-images.githubusercontent.com/53438425/231932787-0781dae8-8dae-45c8-9199-4db2426311b2.png)

**Comment by pionxzh** [comment]
@peterkaminski @patrickwitter Based on the recent bug #119, I think they are the same one. Let me know if you guys still have problem with [v2.6.4](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.6.4)

**Comment by peterkaminski** [comment]
v2.6.4 works for me, thanks!
