### ISSUE TITLE
Option gone after todays update

### ISSUE THREAD

**Issue by AKASGaming** [pionxzh/chatgpt-exporter#119]
![image](https://user-images.githubusercontent.com/25405047/231850183-b619ed5b-635f-475e-8f4b-3e0f6b017eb4.png)
Was there one second, I reloaded the page and then it disappeared

No errors in console either

**Comment by Kreijstal** [comment]
it's gone

**Comment by kyoyacchi** [comment]
I guess it's probably they changed "chat" to "c" in URL. You can add "`@match     https://chat.openai.com/c/*" below other `match`` variables to make it work or wait for next update.

**Comment by sbmsr** [comment]
I've made a PR with the change suggested by @kyoyacchi (ty!).  I've tested it locally and it's working for me.

**Comment by pionxzh** [comment]
Fixed in [v2.6.4](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.6.4)

**Comment by patrickwitter** [comment]
How to upgrade? @pionxzh

**Comment by pionxzh** [comment]
@patrickwitter check https://greasyfork.org/scripts/456055-chatgpt-exporter

**Comment by patrickwitter** [comment]
@pionxzh Installed and still not showing up. New Error as follows
![Screenshot (106)](https://user-images.githubusercontent.com/53438425/231934340-67bba689-df50-45c2-8fa8-e2e83d350ccf.png)

**Comment by pionxzh** [comment]
@patrickwitter  Can you check your script manager? I'm able to see if it's enabled on this page.
![image](https://user-images.githubusercontent.com/9910706/231936227-aaad2c21-2e2e-4c58-bf03-09d7f0c5f771.png)

**Comment by Kreijstal** [comment]
this works if you refresh on a conversation, but not if you go to the main page.

**Comment by pionxzh** [comment]
> this works if you refresh on a conversation, but not if you go to the main page. at least on firefox.

@Kreijstal You mean it's not working on https://chat.openai.com/ ?

**Comment by Kreijstal** [comment]
> > this works if you refresh on a conversation, but not if you go to the main page. at least on firefox.
> 
> @Kreijstal You mean it's not working on https://chat.openai.com/ ?

correct, it works on /c/* but not on openai.com

**Comment by pionxzh** [comment]
It's actually been listed... ok, I will check on firefox
https://github.com/pionxzh/chatgpt-exporter/blob/90ee1b716d5705cd6638ba9ad1dee18d457e69ec/dist/chatgpt.user.js#L13

**Comment by pionxzh** [comment]
@Kreijstal You are right. Turn out Greasemonkey is stricter on this.

**Comment by patrickwitter** [comment]
Still not seeing it @pionxzh What should I do?

**Comment by pionxzh** [comment]
@patrickwitter You might need to diagnose first to see what might be wrong. It would be too difficult for me to help you with limited information.
