### ISSUE TITLE
we need download all chat without select one

### ISSUE THREAD

**Issue by procodeing7** [pionxzh/chatgpt-exporter#120]

**Comment by pionxzh** [comment]
Could you elaborate more on what you want?

**Comment by procodeing7** [comment]
There is a large number of previous conversations stored in ChatGPT, and it can be challenging to Export them individually. Is it possible to implement a feature that allows users to withdraw all past chats at once or specify a date range for Export?

**Comment by Kreijstal** [comment]
you can already do that?

**Comment by pionxzh** [comment]
You have some options like:
1. Export All -> Select All -> Done
2. Wait for #121 to bring in the feature which allows importing data from the official export, and re-export it to another format
3. Just use the official export

Actually I'm not sure what is the challenge you mentioned? You already can withdraw *all* your past chats.

I personally don't want to add the date range feature as it's problematic and kind of too complex.

**Comment by procodeing7** [comment]
ok. Thank you all 👍
