### ISSUE TITLE
Feature Request: generate HTML from export

### ISSUE THREAD

**Issue by bryanschmidty** [pionxzh/chatgpt-exporter#121]
In ChatGPT "Settings" There is an "Export data" link that will email you a JSON file of your chats. I don't know when this was added, nor am I aware of any limitations (number of times or how often you can export), though it doesn't seem like there are any. 

Would it be possible to add a node script that uses your logic to convert that export to different HTML files? or something similar?

**Comment by pionxzh** [comment]
They added it around 2 days ago. I will check what's the data format later.

**Comment by pionxzh** [comment]
Looks like we can reuse the `conversations.json` to generate other formats.
