### ISSUE TITLE
The script is not working now

### ISSUE THREAD

**Issue by FireSK7** [pionxzh/chatgpt-exporter#123]
I just use this script yesterday.

**Comment by Syntax3rror404** [comment]
Looks like openai changed the URL from https://chat.openai.com/chat/<uuid> to https://chat.openai.com/c/<uuid>

You can try to overwrite itthe tampermonkey settings

**Comment by zfuchen** [comment]
Open Tampermonkey Dashboard and click on ChatGPT Exporter then change line 15
`// @match              https://chat.openai.com/chat/*` to `// @match              https://chat.openai.com/c/*`

**Comment by SoEVK** [comment]
// @match              https://chat.openai.com/*

**Comment by pionxzh** [comment]
Fixed in [v2.6.4](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.6.4)
