### ISSUE TITLE
Feature Request: Export chats in the Playground

### ISSUE THREAD

**Issue by bryanschmidty** [pionxzh/chatgpt-exporter#127]
Currently, In the OpenAI playground (https://platform.openai.com/playground), their official export seems to be broken and doesn't export everything. It would be nice to have your formatted exports here too. The playground only keeps 30 days of history, so I'm losing stuff already :( lol.

**Comment by pionxzh** [comment]
I don't have quota to test on it. And they don't give me a chance to buy it too. 😢

**Comment by pionxzh** [comment]
Closing as I don't have the resource for this. 😢 

But I believe it shouldn't be too complex to port this plugin to adapt the playground.
