### ISSUE TITLE
高分屏上截图分辨率过低

### ISSUE THREAD

**Issue by vicename** [pionxzh/chatgpt-exporter#129]
在高分辨率屏幕上截图的时候，生成的图片分辨率没有根据高分屏的缩放倍数进行缩放，导致分辨率过低。希望能修复，或在设置中添加手动选择缩放倍数的选项以便生成更清晰的图片。感谢！

**Comment by pionxzh** [comment]
请问是4K屏还是Mac? 怕我手边没有设备可以测试

**Comment by pionxzh** [comment]
现在新的策略会是尊重萤幕的缩放倍率，并且以 2x 的方式输出

**Comment by vicename** [comment]
感谢，太棒了
