### ISSUE TITLE
存在一些无法顺利导出html和markdown的对话

### ISSUE THREAD

**Issue by Megumism** [pionxzh/chatgpt-exporter#131]
![iFbDyk.gif](https://i.328888.xyz/2023/04/19/iFbDyk.gif)

比如我这里有两个对话，”猫娘聚类程序“和”猫娘助手“，前者的所有导出都没有问题，但是后者只能导出json，按其他的按钮什么也不下载。

插件不是有个批量导出的功能吗，我还试了一下这个，如果批量导出里面不选猫娘助手就可以正常导出，否则导出其他对话也带上猫娘助手就也是什么都不下载，这个问题我实在没有什么头绪，也不知道在其他人那里能不能复现。

**Comment by pionxzh** [comment]
@Megumism 请使用以下步骤帮我找出错误纪录

1. 刷新页面，操作会失败的那个动作
2. 按 `F12` 或是想办法打开你所使用的浏览器的 **开发工具**
3. 切换至 `Console`
4. 你应该会看到一排红红的错误 尽可能的全部截图下来

**Comment by Megumism** [comment]
ctrl+R强制刷新后：
![iGkiQw.png](https://i.328888.xyz/2023/04/20/iGkiQw.png)

再点击导出助手>html后：
![iGkygx.png](https://i.328888.xyz/2023/04/20/iGkygx.png)

> 由于我不能确定这些图片里是否会泄露ID信息，这些图片将在一周后被图床自动删除。

**Comment by pionxzh** [comment]
发布了 2.7.1，帮我看看有没有修复这个问题
应该可以顺利导出，但不知道为什么有些东西API没给回来，不知道内容会不会感觉少东西，可以检查看看

**Comment by pionxzh** [comment]
然后这个截图没有泄漏什么资讯，可以放心

**Comment by Megumism** [comment]
现在可以顺利导出了，但是确实少了东西，对比发现json是完整的记录了从头到尾的对话，但是html和markdown都是不完整的

**Comment by pionxzh** [comment]
@Megumism 不知道方不方便把去敏后的json发出来或是email给我，不知道你遇到了什么样不同的资料结构

**Comment by Megumism** [comment]
已经发送到您Github主页的邮箱，没有去敏，我相信您。解压密码是CatAssistant。

**Comment by pionxzh** [comment]
我知道了 是新的 Plugin 系统 我还在waitlist上没能拿到 😢 (( XMSL 🤣 
感谢你提供的资料 我会把这个挪到另一张 issue

**Comment by pionxzh** [comment]
Moved to #136

**Comment by Megumism** [comment]
好的，辛苦了
