### ISSUE TITLE
Duplicate export problem

### ISSUE THREAD

**Issue by ShiroSakurairo** [pionxzh/chatgpt-exporter#133]
I am aware that someone has already brought up this issue before, and I understand that developers do not like repetitive issues. However, it seems that they have not provided any follow-up information. I have also encountered this problem and I have other feedback to provide, so I am opening a new issue.

https://user-images.githubusercontent.com/56281553/233341247-5228f98a-aa3b-4dec-bb92-c45c5a6e352c.mp4

I am running on Kiwi Browser 111.0.5563.104 with Tampermonkey 4.18.1. The script fails to run with version 2.6.3 after downgrading, but works with version 2.6.4. However, there is an issue with repeated exporting.

![IMG_20230420_182649](https://user-images.githubusercontent.com/56281553/233339782-bef9e2c0-811e-4497-95d2-d05a2dc4555a.jpg)
Another issue is that there are two copy buttons in ChatGPT's response, and both of them seem to work. I'm not sure if this counts as a bug, but I wanted to report it anyway.
Please note that I'm using a translation tool for my English, so there may be some misunderstandings. I apologize for any confusion caused.

**Comment by pionxzh** [comment]
For the two copy buttons issue, I think OpenAI just added their built-in copy button, so I will turn off this feature.

**Comment by pionxzh** [comment]
I think the mobile version might have some sort of bug...  I will add some workaround for it!

**Comment by ShiroSakurairo** [comment]
![IMG_20230420_235900](https://user-images.githubusercontent.com/56281553/233422150-a139976f-bcce-4758-b6fc-53c0411d0130.jpg)

I also found a bug. After I edit my post, the "Edit" button moves to the far right. At this point, no matter how many times I click it, there is no response. I have to stop the script in order to edit again.

**Comment by pionxzh** [comment]
Thanks. I will fix them together.

**Comment by ShiroSakurairo** [comment]
![IMG_20230421_022911](https://user-images.githubusercontent.com/56281553/233456538-5dcc1b92-d614-42c3-9c78-e89a3dacbc42.jpg)
I know it's annoying to give feedback in this way multiple times... so I'm sorry. Similar to the previous issue, if I ask ChatGPT to regenerate a response, the page turning button (I'm not sure what it's called) will overlap with the like button, making it very difficult for me to press the button I want. I think it might be better to move the layout of all the buttons to the right a bit.

**Comment by pionxzh** [comment]
Ye, actually I noticed these buttons' position is not stable enough weeks ago. I just don't want to spend time on fighting with them 🤣 Editing, resizing...all of these will cause some weird behaviors.

**Comment by pionxzh** [comment]
Since OpenAI already provides the official copy button, we can safely remove it.
So the good news is we don't need to modify these buttons anymore.
