### ISSUE TITLE
Script menu unstable on Safari

### ISSUE THREAD

**Issue by hell0github** [pionxzh/chatgpt-exporter#14]
Hi, I still have the issue that the menu didn't show consistently whenever I refresh the ChatGPT webpage using Safari. Does it have something to do with any incompatibility between Tampermonkey and Safari? The menu blinks once whenever refreshed but finally disappeared, though the Tampermonkey extension itself says the script has been enabled normally.

**Comment by hell0github** [comment]
It turns out the menu pops up normally whenever for the first time I open the webpage, but vanishes after refreshed.

**Comment by pionxzh** [comment]
Will check this out  after 12/17, thanks

**Comment by pionxzh** [comment]
Noticed that now they have a pre-checker :/
I will find some way to handle it.

**Comment by pionxzh** [comment]
I just tried it on Safari, and it looks good. We have improved the stability a lot which should already fix the issue.
Let me know if you still see this problem.
