### ISSUE TITLE
Support functioning with chat history disabled

### ISSUE THREAD

**Issue by Nuc1eoN** [pionxzh/chatgpt-exporter#140]
OpenAI has recently introduced the option to turn off history and training (under Settings -> Data Controls).
I have noticed that the exporter does not work correctly when chat history is disabled. It downloads the wrong chat. Can you reproduce? Would be cool if that worked :)

**Comment by pionxzh** [comment]
I think that's expected. The exporter plugin relies on the chat history to function correctly, so disabling it might cause some issues. But what does "downloads the wrong chat" mean? Someone else's chat, some random chat you have in the past, or?

Could you help to list what is working and what is not? Like
- Copy: working
- Export All: no list

**Comment by Nuc1eoN** [comment]
Oh I see I did not know that is the expected outcome.

What I meant is that my prior history/or chats are still saved in the side-panel, but are not accessable. So when I select Export (Copy text, HMTL, JSON, doesn't matter), chatgpt-exporter
seems to download that top most (not accssable through the UI in inkognito mode) chat.

I new to chatgpt-exporter and my hope was, that I could save my chat history in incognito mode. Currently seemingly the only way for me to achieve this is to do a full page screenshot or copy the text to my clipboard, but both options are not very user friendly imho.

Not sure if it is planned for chatgpt-exporter (or possible) to allow downloading chats in incognito mode, but it would be pretty useful :)

**Comment by pionxzh** [comment]
I see. I might need to spend some time to verify what can the script do in the incognito mode.
But a good to have thing is that at least the script should be able to detect if it is in the incognito mode and disable the features accordingly.

**Comment by pionxzh** [comment]
We can detect that by checking `'oai/apps/historyDisabled'` in localStorage. However, fetching the current chat id is a bit challenging and might be hacky. Not sure when will I find a solution for this.

**Comment by pionxzh** [comment]
Status update and sharing finds:

1. Disabled chat cannot be fetched via any API call.
2. The only viable way seems to be sniffing on the event stream / conversation API call
3. I have successfully got part of the result from 2.

Thats all what I have got, I still need to merge the result and rewrite some of the logic.

**Comment by Nuc1eoN** [comment]
Oh my gosh, what a journey :eyes: sorry I did not expect it would be that much work, but thanks a lot for the efforts :pray:

**Comment by pionxzh** [comment]
Due to the lack of time and resources, I decided not to implement this as it requires too many hacks. Hacks also bring a large amount of maintenance cost.

Sorry for the inconvenience.
