### ISSUE TITLE
ZIP without compression

### ISSUE THREAD

**Issue by dmki** [pionxzh/chatgpt-exporter#141]
When exporting as ZIP, it doesn't compress anything. Compression ratio is 100%, when it could be 5%. So I have to re-compress it using 7-zip converter, but I wouldn't have to, if there would be even fastest compression selected.

**Comment by AKASGaming** [comment]
How big are your chats that you need it to be a smaller file size??

**Comment by pionxzh** [comment]
Thanks for bringing it up. I have enabled the best compression rate by default.

**Comment by pionxzh** [comment]
Actually the result is promising, `19.8KB` -> `6.88KB`

**Comment by dmki** [comment]
> How big are your chats that you need it to be a smaller file size??

4.6Mb -> 248Kb

> Actually the result is promising, `19.8KB` -> `6.88KB`

Thanks a lot!
