### ISSUE TITLE
Export to PNG not work

### ISSUE THREAD

**Issue by lolieatapple** [pionxzh/chatgpt-exporter#145]
I tried to export a PNG screenshot, but the exported file is empty. No problem with other formats.

**Comment by pionxzh** [comment]
Hmm I just tested, and it works fine on my side. Have you used this feature before?

**Comment by lolieatapple** [comment]
No, it's the first time I use it.

**Comment by pionxzh** [comment]
Could you provide details about your browser and OS? and what is the exported image? empty image with width and height 0?

**Comment by lolieatapple** [comment]
Chromium Engine Version 113.0.5672.126

**Comment by pionxzh** [comment]
I see, I will test this tomorrow with my M1 Arc.

**Comment by lolieatapple** [comment]
Ok, Thanks!

**Comment by pionxzh** [comment]
Version 0.102.0 (38682)
Chromium Engine Version 113.0.5672.63
MacOS 13.3.1 (M1 chip)

also tested on (Arc Browser Version 0.104.0 (38955))

Both versions works fine on my machine.

1. You might be ab-tested by OpenAI which introduced changes to CSS selector
2. I don't know, maybe check script updates, console errors

**Comment by lolieatapple** [comment]
I got this warning in console window:
3DevTools failed to load source map: Could not load content for chrome-extension://jijileelaefjahodboljljdgfpbjjlac/content/content.main.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

is it matter?

**Comment by lolieatapple** [comment]
OMG, it is good today. thanks a lot~
