### ISSUE TITLE
'Continue generating' 生成的内容没有合并到之前生成的内容中。

### ISSUE THREAD

**Issue by z14git** [pionxzh/chatgpt-exporter#146]
最近的更新中，多了一个 'Continue generating' 的功能。当输出的内容过长，ChatGPT 没有输出完时，它就会显示'Continue generating'按钮，点击它就可以让 ChatGPT 继续输出。
目前发现，'Continue generating' 生成的内容，在导出的时候会单独占一段，并没有合并到之前的输出中。建议合并到一块。

**Comment by pionxzh** [comment]
我以为挺简单的，其实还牵涉到一些其他问题像是 regenerate 的顺序等等，麻了 🤣
