### ISSUE TITLE
无法导出编辑过的消息的记录（当前消息的历史对话记录）

### ISSUE THREAD

**Issue by DumoeDss** [pionxzh/chatgpt-exporter#158]
chatgpt可以编辑消息，重新生成回答，我发现在使用导出功能时，只会导出最后编辑过的消息与回答，而之前的消息都不会导出。
但是历史对话消息在某些情况下是非常重要的，因为可能会在中间某个位置进行分支对话。

**Comment by DumoeDss** [comment]
好吧，那希望可以把分支号加上 e.g. <2/3>

**Comment by pionxzh** [comment]
See #99. 最近状态不太好，有点鸽
