### ISSUE TITLE
help: How to get chatGPT QA-list? (like previous vscode-chatgpt) 

### ISSUE THREAD

**Issue by new4u** [pionxzh/chatgpt-exporter#159]
Thanks for the great job! 

Like previous [vscode-chatgpt,](https://github.com/gencay/vscode-chatgp) it has the web content retrivement of history Q&A list including **Regenerated answers** which very helpful to me.

Like these answers...
<img width="922" alt="image" src="https://github.com/pionxzh/chatgpt-exporter/assets/17016813/5ec6ccee-b182-4fe2-8bdb-dd29a374a763">

Now the plugin of vscode is offline, is there any method to get qa-list by selectquery or your plugin ?

**Comment by pionxzh** [comment]
I'm not sure what is qa-list. You mean this <5/5> thing?

**Comment by new4u** [comment]
yes!

Answers regenerated from the same question are folded by chatgpt. The
former vscode - chatgpt can export it all.


Pionxzh ***@***.***> 于 2023年6月28日周三 10:29写道：

**Comment by pionxzh** [comment]
See #158

**Comment by new4u** [comment]
I noticed that it can export one of the branch .But what I am talking about
is from 1 to 5 , all export. As the previous vs code-chatGPT can be done.

Pionxzh ***@***.***> 于 2023年6月28日周三 12:56写道：

**Comment by pionxzh** [comment]
Could you provide an example export file so that I can check how they export multiple branches?

**Comment by new4u** [comment]
I asked prompt of randomly generate a knowledge map of knowledge domain and can render it with d3 (probably) and then regenerate many times. The screenshot is exported by vscode-chatgpt (https://github.com/gencay/vscode-chatgpt)
![162c3d15371c1235a73a5f87b683303](https://github.com/pionxzh/chatgpt-exporter/assets/17016813/33f370a8-9f00-4ea4-a721-f25b16aad2f3)

**Comment by pionxzh** [comment]
The link you provided in question is broken, so at first I thought that plugin is no longer exists. 

I will need complete file content to analyze the format. Is it possible to provide a shorter and complete example? no screenshot.

And what file format do you actually want to see this feature? HTML or Markdown?

**Comment by new4u** [comment]
Already sent you via email 
***@***.*** ***@***.***>

**Comment by pionxzh** [comment]
Resolved in the mail. Not an issue or request.
