### ISSUE TITLE
When copy chat conversations, it does NOT include user post

### ISSUE THREAD

**Issue by snowman** [pionxzh/chatgpt-exporter#16]
https://github.com/pionxzh/chatgpt-exporter/blob/76d408287c8faae57be4a726ca34fdfddf8c537f/packages/userscript/src/main.ts#L148-L165

Neither selector `'.markdown'` nor `'.w-full > .whitespace-pre-wrap'` exists for user input.

This only export `ChatGPT:` only, like
> ChatGPT:
> Hello! How can I help you today?

![image](https://user-images.githubusercontent.com/16096559/208221336-64cab238-b5ff-4137-a77a-6e7fb019107d.png)

![image](https://user-images.githubusercontent.com/16096559/208221311-2b1cd9fe-909c-43d9-89e6-ba190105020a.png)

**Comment by pionxzh** [comment]
Thanks for the report! They changed the layout. Let me fix it later.

**Comment by pionxzh** [comment]
I just added the support for both ordered list and unordered list
Here is an example:

```
You:
give me the list of top 10 euro countries by population

ChatGPT:
Here is a list of the top 10 European countries by population, based on data from the World Bank:

1. Russia - 144 million
2. Germany - 83 million
3. Turkey - 84 million
4. France - 67 million
5. Italy - 60 million
6. Spain - 47 million
7. Ukraine - 42 million
8. Poland - 38 million
9. Romania - 19 million
10. Netherlands - 18 million

Note that the European Union (EU) is a political and economic union of 27 European countries that are located primarily in Europe. Some of the countries on this list are not members of the EU.

You:
convert this to bullet point

ChatGPT:
Sure, here is the list of top 10 European countries by population in bullet point format:

- Russia: 144 million
- Germany: 83 million
- Turkey: 84 million
- France: 67 million
- Italy: 60 million
- Spain: 47 million
- Ukraine: 42 million
- Poland: 38 million
- Romania
```
