### ISSUE TITLE
Overlapping 

### ISSUE THREAD

**Issue by kyoyacchi** [pionxzh/chatgpt-exporter#164]
Hi, the menu is overlapping on mobile. I can't see markdown and screenshot options. (Kiwi Browser) I guess it happens when i open the menu on "Previous 7 Days" 
![Screenshot_20230820-134911](https://github.com/pionxzh/chatgpt-exporter/assets/63583961/49ad7862-a43c-476d-86eb-041e5073eace)

**Comment by pionxzh** [comment]
oh, let me try some z-index magic
