### ISSUE TITLE
"Export" button is on top of the "Settings" button

### ISSUE THREAD

**Issue by Nayko93** [pionxzh/chatgpt-exporter#166]
Hey

When I try to go to ChatGPT setting, the "Export" button is on top of the "Settings" button, blocking me from clicking on it 

![Capture](https://github.com/pionxzh/chatgpt-exporter/assets/74017582/a027c807-06ef-4702-bbc0-c513d95424a1)

I'm not sure if I'm the only one with that issue ? since it something really annoying but nobody talk about it here...

**Comment by pionxzh** [comment]
Hi, may I know your browser and it's version?
It works on my side.

![image](https://github.com/pionxzh/chatgpt-exporter/assets/9910706/8d1d71bb-a685-4b36-a45b-1658f3afd751)

**Comment by pionxzh** [comment]
Ok. Obviously I'm not using the latest. 😆 
A patch is on the way.

**Comment by pionxzh** [comment]
Fixed in v2.14.3

**Comment by Nayko93** [comment]
I was using a old version of chrome, Version 109.0.5414.120
And yes it's solved now thanks :)
