### ISSUE TITLE
Broken view on share links (mobile)

### ISSUE THREAD

**Issue by kyoyacchi** [pionxzh/chatgpt-exporter#168]
![Screenshot_20230919-183743](https://github.com/pionxzh/chatgpt-exporter/assets/63583961/eaa872dc-af41-4f69-98d4-9719e2a36eb9)
It looks like this.

Example url: https://chat.openai.com/share/bd849a6a-31dc-4e40-b229-3046bef60a4b (not mine. https://greasyfork.org/en/scripts/456055-chatgpt-exporter/discussions/201748)

**Comment by pionxzh** [comment]
![image](https://github.com/pionxzh/chatgpt-exporter/assets/9910706/189907bc-44a9-47fc-afec-8f315598ed2d)

**Comment by kyoyacchi** [comment]
@pionxzh but no option is working except settings and export all(it doesn't work tho, just popup)

**Comment by pionxzh** [comment]
@kyoyacchi what is the behavior you see? It's working on my side...

**Comment by kyoyacchi** [comment]
> @kyoyacchi what is the behavior you see? It's working on my side...

I can't click on HTML, Markdown or JSON or rather, nothing happens when i click on any of them. 

Screenshot option is making me wait then downloads a corrupt file (0B)

**Comment by pionxzh** [comment]
We can no longer access the content of sharing via official API. I will disable these options.

**Comment by pionxzh** [comment]
And the problem of generating empty screenshot is because the photo will be too long on mobile.
See https://html2canvas.hertzen.com/faq#why-is-the-produced-canvas-empty-or-cuts-off-half-way-through
Let me see how can I workaround it.

**Comment by pionxzh** [comment]
OK. Let me update this.
1. I fixed the problem of failing to copy/export by supporting the new message content format `execution_output`
2. The format and visual effect of code and execution_output should be also improved in Markdown and HTML.
