### ISSUE TITLE
Export to HTML doesn't work properly 

### ISSUE THREAD

**Issue by V3TH14** [pionxzh/chatgpt-exporter#173]
Export to HTML does export only some of the current chat's history. Starts normally, goes through first messages, and then after some messages it just cuts off - stops generating.

I've tried it on several web browsers both on mobile and PC (Edge, Chrome, Brave and Firefox) and the feature is still broken.

**Comment by pionxzh** [comment]
Would you willing to share the chat share link or the JSON export so that I can investigate the source of error. You can send it to my email if it's kinda sensitive.

**Comment by 14790897** [comment]
哥，HTML和MARKDOWN都失效了，只能导出对话开头的一小部分
https://chat.openai.com/share/9b64ebc0-24c6-4a86-aab3-d059e5d7408c

**Comment by pionxzh** [comment]
@14790897 感谢你的分享，看来问题是出在使用了 Web browsing with bing 身上

你分享的对话是可以正常全部导出的，因为其已经被处理为可分享的格式，而现在脚本对于 browser plugin 的支持不是很完善，我没办法完全重现你的问题，但我会尝试改进插件所输出的内容，然后咱们再看看是不是能解决问题

**Comment by 14790897** [comment]
@pionxzh 不是那个原因，我刚刚发现如果一个对话有多个提交，只会截取第一个提交忽视后面的提交，而我后面的提交才是真正的我要导出的部分
![image](https://github.com/pionxzh/chatgpt-exporter/assets/121866954/e2929dc5-5487-4b30-8618-400042310706)
这里只会导出第一轮，而第二轮才是我想要的

**Comment by 14790897** [comment]
感觉可以根据导出的json（json是正常的）转换成markdown

**Comment by 14790897** [comment]
我竟然没收到这条消息，我还以为这个问题一直没被处理。现在看到了，确实有很多改进，但是下面这个对话不行https://chat.openai.com/share/f51c6e58-9a4e-4761-9da1-81147abcfadc

**Comment by pionxzh** [comment]
@14790897 不好意思可以导出 JSON 方便测试吗? shared conversation 会被 chatgpt 处理很多，反而无法重现

**Comment by 14790897** [comment]
稍等

**Comment by 14790897** [comment]
兄弟，文件来了

**Comment by pionxzh** [comment]
@14790897 帮我试试这个版本有没有效果

[chatgpt.user.zip](https://github.com/pionxzh/chatgpt-exporter/files/13279695/chatgpt.user.zip)

**Comment by pionxzh** [comment]
好好好 我吃完饭发

**Comment by pionxzh** [comment]
@14790897 released [v2.16.1](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.16.1)

**Comment by 14790897** [comment]
感谢作者
