### ISSUE TITLE
HTML export doesn't follow the user's chain of prompts

### ISSUE THREAD

**Issue by KanchiMoe** [pionxzh/chatgpt-exporter#177]
I've noticed that with an HTML export, it doesn't seem to follow the user's chain of prompts.

For example, I have exported a chat via HTML that says this is the very last message.

Image link: https://github.com/pionxzh/chatgpt-exporter/assets/5897898/a99aa5e8-8065-44b1-bb0e-b26230c653d5

Notice how it says "unease grew".

In ChatGPT itself, this was the 3rd regenerated output from ChatGPT, and there is no follow up to it.

Image link: https://github.com/pionxzh/chatgpt-exporter/assets/5897898/10363dba-29ff-40e1-bfe3-11d11c8e7de8

However, I ended up selecting output 1 and continued with the prompts from there. This is correctly captured in the JSON export, but not in the HTML one.

Image link: https://github.com/pionxzh/chatgpt-exporter/assets/5897898/2dd6accc-9a19-4e71-b8fc-09539f308fa0

**Comment by pionxzh** [comment]
1. What model and plugin were you using in the chat?
2. Can you try exporting text and markdown and see if they also show the wrong message chain (they actually share the same logic)

**Comment by KanchiMoe** [comment]
From the exported JSON, `"model_slug": "text-davinci-002-render-sha",` / ChatGPT 3.5

Using a markdown export, it does seem to follow the correct chain. I also retested exporting a chat as HTML and it does seem to follow the correct chain now, so the issue can be marked as closed.

**Comment by pionxzh** [comment]
Ok, thanks. Let me know if you see the issue again.
