### ISSUE TITLE
Screenshot is failing on the new UI

### ISSUE THREAD

**Issue by pionxzh** [pionxzh/chatgpt-exporter#184]

**Comment by pionxzh** [comment]
Reopen because desktop mode is still buggy; it's a nightmare to debug this...

**Comment by flaviut** [comment]
I personally get better results when I "Export HTML" then 

![image](https://github.com/pionxzh/chatgpt-exporter/assets/5213469/73ee23ec-7aae-4dad-a8d8-432a536b1f16)

and "Save full page" in firefox. [Or in chrome](https://www.howtogeek.com/423558/how-to-take-full-page-screenshots-in-google-chrome-without-using-an-extension/)
