### ISSUE TITLE
Not exporting the entire chat

### ISSUE THREAD

**Issue by vild3r** [pionxzh/chatgpt-exporter#186]
So I am using, violent monkey extension. And i am on kiwi browser for Android. The menu shows correctly and i can export, but my chat is very long, and when i use any of the options, a very small initial portion of the chat gets copied. its the same amount in every format.

**Comment by pionxzh** [comment]
1. Can you check the current installed version?
2. What model and mode you were using? like ChatGPT4 + Browse plugin
3. Can you provide the JSON export so I can investigate further?

**Comment by 14790897** [comment]
[ChatGPT-gpt4counter-2023-11-13.json](https://github.com/pionxzh/chatgpt-exporter/files/13330376/ChatGPT-gpt4counter-2023-11-13.json)
老哥，在’如何定期清除集合recordedIncrements‘提问后面的一个提问中，插件选择了第二个分支，但是我实际上想导出的是第一个分支

**Comment by 14790897** [comment]
应该选择第一个分支，结果选择第二个分支

**Comment by pionxzh** [comment]
可能哪裡有問題，我再看下，你有先裝到最新版嗎，才剛修復新UI的新 selector

**Comment by 14790897** [comment]
是最新版2.17.1

**Comment by pionxzh** [comment]
因为 selector 写错了没注意到 🤣

**Comment by pionxzh** [comment]
Fixed in 2.17.2
