### ISSUE TITLE
Support mathematical formula

### ISSUE THREAD

**Issue by wanzhiyu** [pionxzh/chatgpt-exporter#187]
Hello,

I recently encountered an issue with the markdown export functionality in the latest version of ChatGPT. It appears that mathematical formulas are not being correctly displayed after export.

### Issue Details:
- **Steps to Reproduce:** 
  1. Create a dialog with mathematical formulas using ChatGPT.
  2. Export the document to markdown format.
  3. Observe that the formulas are not correctly displayed in the exported file.

### Expected Behavior:
The exported markdown file should correctly display all mathematical formulas as they appear in the original document.

### Actual Behavior:
The formulas in the exported markdown file are either not visible or incorrectly formatted, making them unreadable.
In ChatGPT:
![image](https://github.com/pionxzh/chatgpt-exporter/assets/18503895/adf3cb99-8a7c-48be-b41a-80abdcc0a3c3)
Exported file In VS Code:
![image](https://github.com/pionxzh/chatgpt-exporter/assets/18503895/8b17f05d-da5a-412c-a09c-ed5b959476d0)
Exported file In Mathtype:
![image](https://github.com/pionxzh/chatgpt-exporter/assets/18503895/0cfdcce9-e619-499f-9d02-a0ffea57f0ce)

I would appreciate any guidance or updates regarding this issue. Thank you for your attention to this matter.

Best regards,

**Comment by pionxzh** [comment]
Can you provide the JSON export so that I can analyze the content? 🙏

**Comment by wanzhiyu** [comment]
> Can you provide the JSON export so that I can analyze the content? 🙏

Sure. Thanks a lot. Here is my json and markdown file. 
[仿真模型.json](https://github.com/pionxzh/chatgpt-exporter/files/13327756/default.json)
[仿真模型.md](https://github.com/pionxzh/chatgpt-exporter/files/13327757/default.md)

**Comment by pionxzh** [comment]
The math formula can render correctly in VSCode by replacing `\[` and `]` with `$`.

```md
1. $\frac{\partial n\_{e}}{\partial t} + \nabla \cdot \Gamma\_{e} = \alpha n\_{e}|\mu\_{e} E| - \eta n\_{e}|\mu\_{e} E| - k\_{pe} n\_{p} n\_{e}$
2. $\Gamma\_{e} = (-\mu\_{e} E n\_{e} - D\_{e} \nabla n\_{e})$
3. $\frac{\partial n\_{\varepsilon}}{\partial t} + \nabla \cdot \Gamma\_{\varepsilon} + E \cdot \Gamma\_{\varepsilon} = R\_{\varepsilon} - (u \cdot \nabla) n\_{\varepsilon}$
4. $\Gamma\_{\varepsilon} = (-\mu\_{\varepsilon} E n\_{\varepsilon} - D\_{\varepsilon} \nabla n\_{\varepsilon})$
```

I'm not sure if it's this library's scope to transform the math syntax, it seems valid (?)

The bad news is that currently the markdown parser we are using does not support the parsing of `\\( your equation \\)` and `\\[ your equation \\]`, which means there is no easy way to convert the syntax for you 😞

**Comment by pionxzh** [comment]
OK. I think it should be safe enough to do a replacement for those `\[\(\)\]`, let me try

**Comment by wanzhiyu** [comment]
It now works really fine.
Thanks a lot! Great work!
