### ISSUE TITLE
Export is using the wrong conversation choice

### ISSUE THREAD

**Issue by 14790897** [pionxzh/chatgpt-exporter#190]
我发现最近的对话可以正常导出，但稍微久一点的对话不能全部导出
如下面的不能正常导出
[ChatGPT-优选IP是什么？-2023-11-18.json](https://github.com/pionxzh/chatgpt-exporter/files/13400352/ChatGPT-.IP.-2023-11-18.json)

**Comment by pionxzh** [comment]
可以描述一下状况吗? 是因为对话节点的选择所以中断还是整个对话都没有 regenerate 但莫名消失了一部份?

**Comment by 14790897** [comment]
第一种

**Comment by pionxzh** [comment]
不好意思，你这个我有点不好复现了，如果愿意 debug 的话可以看下 `getConversationChoice` 结果正不正确，然后另一种可能有问题的是 continue 节点合并导致选择跳位置了

如果稍微看了下没有特别错误的话，把 `getConversationChoice` 的结果发到这里来我再看看

**Comment by 14790897** [comment]
我去，这难度太高了，再说吧

**Comment by pionxzh** [comment]
不好意思，我給個步驟吧，確實我這樣隨口說一句太難了

1. Clone project
2. `pnpm install`
3. `pnpm run dev`
4. 將原先的腳本關閉，改用開發模式安裝的
5. 代碼中搜索 `getConversationChoice` 並在 return 前加上 `console.log('getConversationChoice', nodes, conversationChoices)
https://github.com/pionxzh/chatgpt-exporter/blob/c9c76890ed676c0d7192bd1fe1f4181283db677d/src/page.ts#L85-L98

**Comment by 14790897** [comment]
大佬，我来了，使用pnpm dev安装插件之后，网页上没有出现导出按钮

**Comment by 14790897** [comment]
要pnpm build，手动加载才有按钮

**Comment by 14790897** [comment]
```
userscript.html?name=ChatGPT-Exporter.user.js&id=24936dc9-3c77-48d5-babb-f7a7f0fdfad2:1146 getConversationChoice (247) [null, null, null, span.flex-grow.flex-shrink-0.tabular-nums, null, span.flex-grow.flex-shrink-0.tabular-nums, null, span.flex-grow.flex-shrink-0.tabular-nums, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, span.flex-grow.flex-shrink-0.tabular-nums, null, null, null, null, null, null, null, null, null, null, null, null, null, span.flex-grow.flex-shrink-0.tabular-nums, null, null, null, null, null, span.flex-grow.flex-shrink-0.tabular-nums, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, span.flex-grow.flex-shrink-0.tabular-nums, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, span.flex-grow.flex-shrink-0.tabular-nums, null, span.flex-grow.flex-shrink-0.tabular-nums, …][0 … 99][100 … 199][200 … 246]length: 247[[Prototype]]: Array(0) (247) [null, null, null, 2, null, 1, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, 1, null, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 1, null, 1, …]
index.ts-14ba51bb.js:1 manualModification
_app-35c14f0b7485bd2e.js:11 
```

**Comment by 14790897** [comment]
上面是按照要求使用console输出的内容，下面的md文件导出有问题
[ChatGPT-php-数据库.json](https://github.com/pionxzh/chatgpt-exporter/files/13705455/ChatGPT-php-.json)
[ChatGPT-php-数据库.md](https://github.com/pionxzh/chatgpt-exporter/files/13705457/ChatGPT-php-.md)

**Comment by 14790897** [comment]
我在看源代码了，感觉这个代码写得很标准

**Comment by 14790897** [comment]
是不是通过api获取的原始数据不能显示用户的选择路径才需要从页面上获取网页数据？

**Comment by pionxzh** [comment]
是的，API 不管用户选到什麽路径，这些都是 ChatGPT 前端管的状态，所以只好从 UI 上重新抓取回来

**Comment by 14790897** [comment]
它前端能做的我们也能做
我觉得可以从API返回的数据最底层开始从下往上遍历， 找到一个节点它的Children包含提问的id，那么这个就是他的父节点

**Comment by 14790897** [comment]
我感觉我找到了正确的思路，读取前端的数据总归是不靠谱的

**Comment by 14790897** [comment]
大佬，有没有那种可以用api获取的Json测试转换效果的方法？

**Comment by pionxzh** [comment]
我一般是直接魔改 call API 的地方。。

**Comment by pionxzh** [comment]
https://github.com/pionxzh/chatgpt-exporter/blob/c9c76890ed676c0d7192bd1fe1f4181283db677d/src/api.ts#L288

直接硬改这个

**Comment by 14790897** [comment]
好的，也可以

**Comment by 14790897** [comment]
https://github.com/pionxzh/chatgpt-exporter/blob/c9c76890ed676c0d7192bd1fe1f4181283db677d/src/api.ts#L475
这个链表有什么作用吗？

**Comment by pionxzh** [comment]
> 这个链表有什么作用吗？
把API返回的数据 (Map/List) 转为一个符合整个聊天顺序的 List

**Comment by 14790897** [comment]
我看你是把所有节点都放在result里，没有使用current

**Comment by 14790897** [comment]
‘’‘
import json


def find_bottom_most_node(conversation_data):
    """
    Finds the bottom-most node in the conversation, which is the node without any children.

    :param conversation_data: The conversation data in a nested dictionary format.
    :return: The ID of the bottom-most node, or None if not found.
    """
    if not isinstance(conversation_data, dict):
        raise TypeError("Conversation data must be a dictionary.")
    try:
        for node_id, node in reversed(conversation_data.items()):
            # Ensure that 'node' is a dictionary
            if not isinstance(node, dict):
                raise TypeError(f"Node {node_id} is not a dictionary.")
            if "children" not in node:
                raise KeyError(f"'children' key not found in node {node_id}.")
            if not node.get("children"):  # Check if the node has no children
                return node_id
    except Exception as e:
        print(f"Error finding bottom-most node: {e}")

    return None


def extract_conversation_path(conversation_data, start_node_id):
    """
    Extracts the conversation path starting from the given node and going up to the root.

    :param conversation_data: The conversation data in a nested dictionary format.
    :param start_node_id: The ID of the starting node (bottom-most node in the conversation).
    :return: A list of nodes representing the conversation path from the start node to the root.
    """
    path = []
    current_node_id = start_node_id

    while current_node_id:
        # Get the current node
        node = conversation_data.get(current_node_id)
        if node is None:
            break  # Node not found

        # Add the current node to the path
        path.append(node)

        # Move to the parent node
        current_node_id = node.get("parent")

    return path[::-1]  # Reverse the path to start from the root


def extract_full_conversation(conversation_data, start_node_id):
    """
    Extracts the full conversation path along with message contents, starting from the given node and going up to the root.

    :param conversation_data: The conversation data in a nested dictionary format.
    :param start_node_id: The ID of the starting node (bottom-most node in the conversation).
    :return: A list of tuples, each containing the node ID and its message content, representing the conversation path.
    """
    full_conversation = []
    current_node_id = start_node_id

    while current_node_id:
        # Get the current node
        node = conversation_data.get(current_node_id)
        if node is None:
            break  # Node not found

        # Extracting the message content if available
        message = node.get("message", {})
        content = message.get("content", {})
        parts = content.get("parts", [])
        message_text = " ".join(
            parts
        )  # Joining parts to form the complete message text
        print("message_text:", message_text)
        # Add the node ID and message text to the conversation
        full_conversation.append((current_node_id, message_text))

        # Move to the parent node
        current_node_id = node.get("parent")

    return full_conversation[::-1]  # Reverse to start from the root


file_path = "./example.json"  # Replace with the actual file path
try:
    # Load JSON data from the file
    with open(file_path, "r", encoding="utf-8") as file:
        conversation_data = json.load(file)
        # print(conversation_data)
except Exception as e:
    print(f"Error reading or processing the file: {e}")

conversation_data = conversation_data["mapping"]  # Convert to a dictionary~
# 获取最底部节点的ID
bottom_most_node_id = find_bottom_most_node(conversation_data)
print("find bottom_most_node_id:", bottom_most_node_id)
# 然后使用这个ID来提取对话路径
if bottom_most_node_id:
    conversation_text = extract_full_conversation(
        conversation_data, bottom_most_node_id
    )
    # 指定要保存的文件名
    file_name = "conversation_output.txt"

    # 使用 with 语句打开文件，确保文件正确关闭
    with open(file_name, "w", encoding="utf-8") as file:
        # 遍历对话中的每个节点
        for node_id, message_content in conversation_text:
            # 将节点ID和消息内容写入文件
            file.write(f"Node ID: {node_id}\nMessage Content:\n{message_content}\n\n")
else:
    print("No bottom-most node found.")

’‘’

**Comment by 14790897** [comment]
话说这个项目有必要用typescript吗？一大堆定义看着好复杂

**Comment by 14790897** [comment]
我是新手，我也不是特别懂

**Comment by pionxzh** [comment]
@14790897 你拉一下最新，看看 https://github.com/pionxzh/chatgpt-exporter/commit/7d830723dba87e46b278831aad16acce72c418e5 是不是修好了问题

**Comment by 14790897** [comment]
不行，先睡觉了

> @14790897 你拉一下最新，看看 [7d83072](https://github.com/pionxzh/chatgpt-exporter/commit/7d830723dba87e46b278831aad16acce72c418e5) 是不是修好了问题
