### ISSUE TITLE
chat.zhile.io 升级成为pandoar-next,现在后端的API是和官方一样的,但是当我把接口改成正确的之后却无法获取有效的accesstoken，导致下载文件失败

### ISSUE THREAD

**Issue by 14790897** [pionxzh/chatgpt-exporter#194]
pandora: https://github.com/pandora-next/deploy
接口: https://chat1.zhile.io/api/auth/session
估计现在作者不允许这么做

**Comment by 14790897** [comment]
解决方法可能是向官方网站请求accesstoken

**Comment by pionxzh** [comment]
适配了新接口
跟着下一次 release，急用的话手动打包下

**Comment by 14790897** [comment]
哦，pandora用的是X-Authorization

**Comment by 14790897** [comment]
大佬看这个请求的话是用浏览器的开发者工具吗？

**Comment by pionxzh** [comment]
对，但我没有很仔细看，可能是他的 proxy 要求的

**Comment by pionxzh** [comment]
Released in [v2.19.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.19.0)

**Comment by pionxzh** [comment]
#211
