### ISSUE TITLE
Add `Archive` button to Export Conversations dialog

### ISSUE THREAD

**Issue by zyf722** [pionxzh/chatgpt-exporter#199]
Two weeks ago, OpenAI added [archived chats](https://twitter.com/OpenAI/status/1737517702766633063) to ChatGPT, which allows you to remove chats from the sidebar without deleting them. Archived chat sessions will disappear from the sidebar and can be managed in the archive conversations section of the settings page.

![](https://github.com/pionxzh/chatgpt-exporter/assets/35839367/d44cbdc7-482e-4a02-a347-58cd4263e4a3)

Considering that export and delete chats in bulk are now fully supported in **Export Conversations**, it would be greatly helpful to managing chats if a batch-archiving button could be added to the same dialog.

![](https://github.com/pionxzh/chatgpt-exporter/assets/35839367/b12c0149-697d-4872-893e-01f538bcb230)

**Comment by pionxzh** [comment]
Good idea. I didn't notice there is a new feature.

**Comment by pionxzh** [comment]
Added. And I also fixed the color of upload icon 🙏 
![image](https://github.com/pionxzh/chatgpt-exporter/assets/9910706/21a50899-5f1b-496c-a920-131044849f55)

**Comment by pionxzh** [comment]
Released in [v2.19.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.19.0)
