### ISSUE TITLE
Improve screenshot with `modern-screenshot`

### ISSUE THREAD

**Issue by pionxzh** [pionxzh/chatgpt-exporter#200]
https://github.com/qq15725/modern-screenshot

Everything looks good. But there are two issues:
- [ ] Scroll Bar (should be able to hide them by adding CSS)
- [ ] Weird text overflow

![ChatGPT-Test_Point_in_Plane](https://github.com/pionxzh/chatgpt-exporter/assets/9910706/dbd66339-2483-4193-ad9a-41a359714259)

**Comment by kyoyacchi** [comment]
I'd like to tell one more thing. It looks like this on mobile. I guess think counts as "weird text overflow" 
![chatgpt-ChatGPT_2024-02-19 (2)](https://github.com/pionxzh/chatgpt-exporter/assets/63583961/93787da3-a677-4d7f-8bca-eb3f13e61184)

**Comment by pionxzh** [comment]
With the modern-screenshot? or the current implementation?

**Comment by kyoyacchi** [comment]
> With the modern-screenshot? or the current implementation?

Current

**Comment by pionxzh** [comment]
okok. I will check what happened. This is kind of an old issue haha.

**Comment by pionxzh** [comment]
@kyoyacchi I just released v2.22.0, which contains a fix for the text issue you mentioned. (See #216)

**Comment by pionxzh** [comment]
I will close this issue since the incentive to switch to this library is not that strong currently. I will open it back if things change.
