### ISSUE TITLE
Only latter section of chat exporting (data-testid has discontinuities)

### ISSUE THREAD

**Issue by jimpala** [pionxzh/chatgpt-exporter#204]
Thanks for creating this fantastic extension!

I've recently run into an issue that if I start a conversation in my browser, then I resume the conversation on the iOS app, then later go to export, the full chat doesn't appear to export for Markdown or HTML. Only the section of the conversation picked up on the iOS app exports.

It looks to me that this might be indicated by discontinuities in the `data-testid` HTML attribute:

<img width="835" alt="Screenshot 2024-01-17 at 12 03 52" src="https://github.com/pionxzh/chatgpt-exporter/assets/16269591/5ea9f83a-0180-4459-bc44-91af01ee0e60">

In this case, only the conversation from `data-testid="conversation-turn-22"` onwards is exported, seemingly indicated by `conversation-turn-21` not existing.

**Note** that this only seems to be an issue with Markdown and HTML export. The screenshot export still grabs the whole conversation.

**Comment by pionxzh** [comment]
ping

**Comment by 14790897** [comment]
pong

**Comment by pionxzh** [comment]
close due to inactivity
