### ISSUE TITLE
❤️ Thanks for this + Usability Review

### ISSUE THREAD

**Issue by porg** [pionxzh/chatgpt-exporter#206]
I love the possibility to backup chatbot conversations…
1. and preserve rich text formatting (near) lossless and as storage-efficient as possible,
    - you have done a great job in both regards!
2. with the export function injected very well within the ChatGPT UI and the walktrhough being very efficient,
    - by facilitating hover as a trigger
    - and being organized very ergonomically/efficiently
    - therefore meaning near-null mental distraction, allowing me perfectly to remain on my train of thought
3. and having customizable file names into which I can integrate several name token,
    - Thereby file archiving take me almost no overhead
4. and having a "Save all" button which downloads all format as a ZIP archive.
    - Again a big time saver and avoidance of mental distraction.

**Comment by pionxzh** [comment]
Thanks 🙏
