### ISSUE TITLE
Generalize codebase to also support other AI chatbots

### ISSUE THREAD

**Issue by porg** [pionxzh/chatgpt-exporter#207]
- First: #206 
- As you have already a great UX and feature collection for archiving AI chatbot conversation,
  - currently particulalry for ChatGPT,
- it may be worth considering to generalize the codebase and to support other chatbots too.
  - with many general features being re-usable
  - and likely very few being chatbot specific

**Comment by porg** [comment]
If the project would indeed go into that direction, the project name would likely need to reflect that genralization.
- Name proposals in followup messages, so that they can be voted/reacted upon.

**Comment by porg** [comment]
chatbot-exporter

**Comment by porg** [comment]
chatbot-archiver

**Comment by porg** [comment]
hallucination-preservation

**Comment by porg** [comment]
botled or botllled (for brand recognition)

### A humurous, slightly philosophical, wordplay with manifold associations:
- Mainly
  - "bot" as in robot
  - "bottled" as in preserved (in a bottle) or as in "get the genie (AI) into the bottle"
- Secondary
  - "bot led"  as in "converation led by a bot" or "the bot is in the lead" or "you lead a conversation together with a bot" or similar interpretations.

**Comment by pionxzh** [comment]
As stated in #208: 
> This project is quite specific to the chatgpt API. There is no plan to extend its supported range to other services.

We also extended its functionality to support other chatgpt-powered web services. See example: #143, #194

So, the name of this project still describes the goal and scope well. 🙏

**Comment by porg** [comment]
- Thanks for your reaction.

- So the only involvement of this your project into my affairs then will be that I will refer your project as a UX best practice to developers of similar exporters for Bard et all. My compliments agains!
