### ISSUE TITLE
Support for: Google Bard

### ISSUE THREAD

**Issue by porg** [pionxzh/chatgpt-exporter#208]
- Either #207
  - and then add Bard support as a module.
- Or by forking as a standalone project, if the differences are too much.
- But from an efficiency/community standpoint I hope for the more general approach

Curious to read your reaction!

**Comment by pionxzh** [comment]
This project is quite specific to the chatgpt API. There is no plan to extend it's supported range to other services.

Feel free to fork it if you like the UI/UX. I can mention that project in README.
