### ISSUE TITLE
Pandora is dead

### ISSUE THREAD

**Issue by pionxzh** [pionxzh/chatgpt-exporter#211]
- https://github.com/pandora-next/deploy/issues/519

- [你们赢了，但我却没有输](https://linux.do/t/topic/1051)

相关服务器也已经下线，我会逐渐清理代码中失效的 zhile / oaifree 内容，但保留 `API_MAPPING` 供大家自行拓展

我对 GPT 共享服务并不是太了解，如果有其他想法也可以提出讨论

**Comment by 14790897** [comment]
好的

**Comment by pionxzh** [comment]
#212 merged
