### ISSUE TITLE
The characters will overlap when exported as image, especially for chinese

### ISSUE THREAD

**Issue by tianzhich** [pionxzh/chatgpt-exporter#216]

**Comment by tianzhich** [comment]
There must be some problems with github uploader. I can't upload the screenshot.

**Comment by pionxzh** [comment]
I have seen this bug before. But it now works correctly on my machine. Can you still reproduce it?

![ChatGPT-王家卫的失恋](https://github.com/pionxzh/chatgpt-exporter/assets/9910706/496793ef-7920-4db6-87ff-2dca8eaf4b2f)

**Comment by tianzhich** [comment]
![ChatGPT_-_Emma_Speaking_Tutor-2024-02-23](https://github.com/pionxzh/chatgpt-exporter/assets/33218310/6e4a2254-fcbc-4e2a-8048-d16b869941c0)

**Comment by pionxzh** [comment]
过两天会跟其他 fix 一起 release
