### ISSUE TITLE
Doesn't export the whole conversation

### ISSUE THREAD

**Issue by Nalci** [pionxzh/chatgpt-exporter#218]
Hello,
I was happy to find a good export tools for ChatGPT. Unfortunatly only a few conversation items of some chats getting exported when I choose any option but json. Is there anything I have to set up?
Thanks.

**Comment by pionxzh** [comment]
Hi, I believe this a bug. Can you share the exported json here or send it to my mail, so that I can inspect the issue?

**Comment by pionxzh** [comment]
pionxzh@csie.io

**Comment by Nalci** [comment]
I sent the file to your email. Thank you!

**Comment by pionxzh** [comment]
I'm currently occupied by IRL things. This will be scheduled to be fixed on 3/14. Sorry for the inconvenience.

**Comment by pionxzh** [comment]
v2.1.2 has been released with the fix. @Nalci can you help to verify?

**Comment by Nalci** [comment]
Yep, it fixed it! Thank you both so much.
