### ISSUE TITLE
Request for Contribution Guidelines

### ISSUE THREAD

**Issue by Notarin** [pionxzh/chatgpt-exporter#22]
I would greatly appreciate it if guidelines for contributing were defined in the [README.md](https://github.com/pionxzh/chatgpt-exporter/blob/master/README.md) or in a new file called CONTRIBUTING.md.

Clear guidelines can greatly improve the efficiency and effectiveness of contributions by providing information on how to properly submit changes, what files should be included, and how commit messages should be formatted. This is especially important when working with new technologies and projects. I believe that having defined guidelines would help streamline the contribution process for all involved. Thank you for considering this request.

**Comment by pionxzh** [comment]
I will provide one later. Thanks for bringing it up.

**Comment by Notarin** [comment]
Thank you, it looks great!
