### ISSUE TITLE
Exporter Not Working for Workspaces Under GPT Team License

### ISSUE THREAD

**Issue by Crockan** [pionxzh/chatgpt-exporter#220]
We have identified a malfunction in the exporter tool within our GPT team workspace. Specifically, the buttons for exporting in Markdown, JSON, and HTML formats are unresponsive upon clicking. However, the "Screenshot" button functions as intended.

### Expected Behavior
All exporter tool buttons, including those for Markdown, JSON, and HTML, should function properly and allow for the export of dialogues in the respective formats.

### Actual Behavior
The buttons for exporting in Markdown, JSON, and HTML formats are unresponsive, while the "Screenshot" button operates as expected.

This issue was only observed in workspaces under the Team License and everything functions normally under the individual Plus License

### Environment
ChatGPT Exporter version: 2.21.0
Operating System: Windows 11
Browser: Microsoft Edge 122.0.2365.66

**Comment by pionxzh** [comment]
This should be a bug, but I'm not sure if I can find any information about how the team license works.

I'm currently occupied by IRL things. This will be scheduled to be fixed on 3/15. Sorry for the inconvenience.

**Comment by pionxzh** [comment]
Can you share the screenshot of [F12] -> [Console] after choosing export to markdown?

**Comment by Crockan** [comment]
![image](https://github.com/pionxzh/chatgpt-exporter/assets/45941794/63db78fa-6198-4b7d-bf09-8203d21f6787)
Here it is. Sorry for the wait.

**Comment by pionxzh** [comment]
Thanks for the information. I'm currently on a trip, this will be delayed to 3/26.

If you know how to code and want to work on the fix, pr welcome!

**Comment by pionxzh** [comment]
I have started fixing this. But it might take a while as I don't have a team account 🙏

**Comment by computersrmyfriends** [comment]
Even I am facing the same issue. Not usable on my teams account.

**Comment by computersrmyfriends** [comment]
@pionxzh  Great work! It works. 🙏👏

**Comment by IlyaRice** [comment]
@pionxzh All json formats, html and markdown works now. Thank you!

**Comment by pionxzh** [comment]
Nice.

**Comment by jgod** [comment]
Is it still working for you guys? I don't see the button despite having it installed and enabled.
