### ISSUE TITLE
What is the template to build this script

### ISSUE THREAD

**Issue by 14790897** [pionxzh/chatgpt-exporter#221]
我觉得你的模板不错

**Comment by pionxzh** [comment]
i didn't use existing template. But you can copy the structure and use it in your poject.

**Comment by 14790897** [comment]
You can create a template repository and I will star it!

**Comment by pionxzh** [comment]
Then, you can probably use my friend's template. It's based on this project's structure.
https://github.com/kiangkuang/userscript-typescript-template
