### ISSUE TITLE
Domain name changed, breaks script

### ISSUE THREAD

**Issue by KanchiMoe** [pionxzh/chatgpt-exporter#232]
The domain name for ChatGPT has changed (or is in the process of changing) from `chat.openai.com` to `chatgpt.com`.

The login screen is still on openai but once logged in, you are redirected to chatgpt.com.

**Comment by pionxzh** [comment]
I think you got ab tested, I can still use `chat.openai.com`. 🤔 

And `chatgpt.com` will redirect me to `chat.openai.com`. Do you have the source of this news?

**Comment by geocell** [comment]
I am experiencing the same issue. There is a redirect, but from chat.openai.com to chatgpt.com, and Tampermonkey will then not be able to identify the page. I tried to copy/paste/add/adapt all the match statements to include chatgpt.com, but that does not seem to be sufficient. I got a HTML export menu entry, but no follow-up action.

**Comment by pionxzh** [comment]
I see. Then I think this is something really happening.

**Comment by pionxzh** [comment]
I just updated the script to make it work on `chatgpt.com`. Thanks @geocell for testing out the changes needed. 🙏
