### ISSUE TITLE
Is there any plan to support new.oaifree.com?

### ISSUE THREAD

**Issue by Cranberrycrisp** [pionxzh/chatgpt-exporter#236]

**Comment by pionxzh** [comment]
Let me test it later. The forum is currently invite-only, I couldn't easily check some of their announcements and discussions.

**Comment by Cranberrycrisp** [comment]
Thanks! Here's the invite link: 
https://linux.do/invites/to4NEdJ1Ui

**Comment by pionxzh** [comment]
Thanks. But 🤔 
<img width="1157" alt="image" src="https://github.com/pionxzh/chatgpt-exporter/assets/9910706/593b837e-d915-4c02-89fa-cd44f9f3674c">

**Comment by Cranberrycrisp** [comment]
https://linux.do/invites/X3YTRFJwAu

**Comment by pionxzh** [comment]
有了谢谢

**Comment by pionxzh** [comment]
Please help me verify if it woks. 🙏

**Comment by Cranberrycrisp** [comment]
Effective, it works very well. Thank you!
