### ISSUE TITLE
Buttons still disappear upon loading saved chats.

### ISSUE THREAD

**Issue by Notarin** [pionxzh/chatgpt-exporter#24]
commit 224a51f79020778d78d116fe0de0221f80d19a2b was supposed to fix this issue, but it appears to still be present.

- Version:
	- 1.3.2
- Browser:
	- Chrome (Unstable) AKA "chrome developer edition"

**Comment by Notarin** [comment]
I forgot to mention that they do appear upon visiting the URL, by clicking a link, or refreshing the page, but the action of *re*-rendering the page causes the buttons to unrender.

**Comment by pionxzh** [comment]
Do you have stable steps to reproduce this?
I tried refreshing, clicking on chat, Editing, and Deleting. But none of these trigger the disappearance.

**Comment by Notarin** [comment]
Sure, I can produce screenshots.
![image](https://user-images.githubusercontent.com/25104390/209056348-446f1eb6-f389-476d-b6c1-fccff47db68c.png)
Buttons visible:
![image](https://user-images.githubusercontent.com/25104390/209056828-a09d3eb2-f7f3-41a9-a094-9176d64015cf.png)
Upon clicking "Minecraft seed near portal":
![image](https://user-images.githubusercontent.com/25104390/209056886-8511993e-46ae-4bb6-b3b8-d1a02b697528.png)
As you can see, upon clicking the link, the buttons disappear.

**Comment by pionxzh** [comment]
Hmm ok... switching between chat is ok on my side. I will try the developer edition.

**Comment by Notarin** [comment]
Reproduced in normal chrome

**Comment by pionxzh** [comment]
Yep. Actually, the problem is that the dev version works fine, but the bundled (production) version is not working as intended.

**Comment by Notarin** [comment]
I'm confused on what youre talking about the version of, dev version of chatgpt-exporter or dev version of chrome?

**Comment by pionxzh** [comment]
oh, the dev chatgpt-exporter script that you installed by running `pnpm dev`

**Comment by Notarin** [comment]
ah, that clears it up allot.

**Comment by pionxzh** [comment]
Turn out this is an interesting issue 🤣

**Comment by Notarin** [comment]
@pionxzh 
Confirmed as fixed

- Version:
	- 1.3.3
- Browser:
	- Chrome (Unstable) AKA "chrome developer edition"
