### ISSUE TITLE
Formula export failure

### ISSUE THREAD

**Issue by kwasposer** [pionxzh/chatgpt-exporter#241]
Hello,

When I export the ChatGPT chat to Markdown, the closing formula bracket is incorrect. It should be \] but it appears as ], causing the formula to render improperly.

**Comment by pionxzh** [comment]
Hi, thanks for reporting this. Can you share the json and markdown export of the chat for further inspection?
Send it here or to my mail 🙏

**Comment by pionxzh** [comment]
Close due to the inactivity. If you experience the problem again, feel free to reopen this issue and provide more details.
