### ISSUE TITLE
Export only the selected text

### ISSUE THREAD

**Issue by Nalci** [pionxzh/chatgpt-exporter#249]
I often want to only export some selected text and not the whole conversation. Would there be a way to add this?

**Comment by pionxzh** [comment]
I just wanted to clarify the request. What you want is a way to select the text and copy the markdown or something? Would you select text across each chat item? How about images and other non-simple text things?

**Comment by pionxzh** [comment]
I would imagine a reasonable interaction design for this scenario:
- Click to enable the selection mode, in this mode, you can choose the chat blocks you want to export, after all selection is done, choose the format and click export.
- In selection mode, all chat blocks' heights are limited to 2-3 lines. There is a check box on the left side of the chat block.

**Comment by Nalci** [comment]
That sounds like what I had in mind! 

I would be totally happy with chat blocks and not random text

**Comment by pionxzh** [comment]
Nice. I will think about it. Not sure how complex it would be to implement.
