### ISSUE TITLE
Fix: remove unnecessary use of comma operator in code

### ISSUE THREAD

**Issue by AntlerPotato** [pionxzh/chatgpt-exporter#250]
**Description:**

While reviewing the source code, I identified an unnecessary use of the comma operator. The specific code segment is:

```javascript
e.textContent=n,document.head.append(e)
```

**Problem:**

The comma operator evaluates both the left and right expressions but only returns the value of the right expression. In this context, its use is redundant and can be replaced with a semicolon to separate the two statements, enhancing code readability and maintainability. This change will also prevent the "unexpected use of comma operator" error message.

**Proposed Solution:**

Replace the comma with a semicolon:

```javascript
e.textContent = n;
document.head.append(e);
```

By implementing this change, the code will adhere to best practices, improving its clarity and reducing potential errors.

**Comment by pionxzh** [comment]
The code snippet you mentioned is injected by [vite-plugin-monkey/src/node/option.ts](https://github.com/lisonge/vite-plugin-monkey/blob/d8127bd6d86966df810b93031bbac8a83f9963b6/packages/vite-plugin-monkey/src/node/option.ts#L237-L239)

And the `,` in the statement is not a "comma operator", it simply serves as a separator.
