### ISSUE TITLE
Support russian language

### ISSUE THREAD

**Issue by xguest** [pionxzh/chatgpt-exporter#254]
I have a proposal ru.json, 

Very good and necessary project

Hi, You wrote.
` Hi, can you put a PR on GitHub?`

Full pull request, I already deleted mine, re-translated only the messages.
I can translate into Polish and Ukrainian

`json
{
  "title": "ChatGPT Exporter",
  "ExportHelper": "Export",
  "Setting": "Setting",
  "Language": "Язык",
  "Copy Text": "Копировать текст",
  "Copied!": "Скопировано!",
  "Screenshot": "Скриншот",
  "Markdown": "Markdown",
  "HTML": "HTML",
  "JSON": "JSON",
  "Archive": "Архивировать",
  "Save": "Сохранить",
  "Delete": "Удалить",
  "Select All": "Выбрать все",
  "Export": "Экспорт",
  "Error": "Ошибка",
  "Loading": "Загрузка",
  "Preview": "Пре просмотр",
  "File Name": "Имя файла",
  "Export All": "Экспортировать все",
  "Exporter Settings": "Настройки экспортера",
  "Export Dialog Title": "Экспортировать беседы",
  "Invalid File Format": "Неверный формат файла",
  "Export from official export file": "Экспорт из официального экспортного файла",
  "Export from API": "Экспорт из API",
  "Available variables": "Доступные переменные",
  "Conversation Timestamp": "Временная метка разговора",
  "Conversation Timestamp Description": "Будет показано на странице.",
  "Enable on HTML": "Включить для HTML-файлов",
  "Enable on Markdown": "Включить для файлов Markdown",
  "Use 24-hour format": "Используйте 24-часовой формат (например, 23:59)",
  "Export Format": "Формат экспорта",
  "Export Metadata": "Экспорт метаданных",
  "Export Metadata Description": "Добавляйте метаданные в экспортированные файлы Markdown и HTML.",
  "OpenAI Official Format": "Официальный формат OpenAI",
  "Conversation Archive Alert": "Вы уверены, что хотите архивировать все выбранные разговоры?",
  "Conversation Archived Message": "Все выбранные разговоры были заархивированы. Пожалуйста, обновите страницу, чтобы увидеть изменения.",
  "Conversation Delete Alert": "Вы уверены, что хотите удалить все выбранные разговоры?",
  "Conversation Deleted Message": "Все выбранные разговоры были удалены. Пожалуйста, обновите страницу, чтобы увидеть изменения.",
  "Please start a conversation first": "Пожалуйста, начните разговор первым."
}
[ru.json](https://github.com/user-attachments/files/16905993/ru.json)
`

**Comment by pionxzh** [comment]
I have submitted a PR with the attached content. A few changes were made based on ChatGPT's suggestion. Please help to review them 🙏

**Comment by xguest** [comment]
I looked, maybe I sent you the wrong version.
If literally (letter by letter) then `Setting` => `Настройка` but they don't say that.
I left the plural `Setting` => `Parameters`, that is, many parameters.

Я посмотрел, возможно, я отправил вам не правильную версию.
Если буквально(по буквам) то `Setting` => `Настройка` но так не говорят.
У себя я оставил множественное число `Setting` => `Параметры`, то есть много параметров.

**Comment by xguest** [comment]
The translation looks correct, but there are a few places where it could be made more natural for Russian-speaking users:
Перевод выглядит корректным, но есть несколько мест, где можно сделать его более естественным для русскоязычных пользователей:

1. `"Preview": "Пре просмотр"` — It would be better to translate it as **"Предпросмотр"**.
1. `"Preview": "Пре просмотр"` — лучше будет перевести как **"Предпросмотр"**.

2. `"Use 24-hour format": "Use 24-hour format (eg 23:59)"` — better translated as **"Использовать 24-часовой формат (например, 23:59)"**.
2. `"Use 24-hour format": "Используйте 24-часовой формат (например, 23:59)"` — лучше перевести как **"Использовать 24-часовой формат (например, 23:59)"**.

**Comment by pionxzh** [comment]
I see. Thanks. I have merged the PR. It will be release in a few days.

**Comment by xguest** [comment]
No need to thank me, if you need anything, just ask!
