### ISSUE TITLE
The export button cannot be seen in the current version of chatgpt.

### ISSUE THREAD

**Issue by HHGGHH1995** [pionxzh/chatgpt-exporter#258]
The export button cannot be seen in the current version of chatgpt.

**Comment by pionxzh** [comment]
I feel the root cause is hydration failed. The force re-rendering blown up the injected menu.

**Comment by pionxzh** [comment]
v2.25.0 should fix the issue.

**Comment by pionxzh** [comment]
@rndwalker simply delaying onloadSafe won't entirely fix the issue. The injected CSS is also removed by libraries like react-helmet.

**Comment by 14790897** [comment]
All google Chrome plugin and Grease Monkey script both fail on chatgpt website.
what's up

**Comment by pionxzh** [comment]
@14790897 You might need to upgrade your script manager to manifest v3. Please check their migration guide.

**Comment by 14790897** [comment]
![image](https://github.com/user-attachments/assets/e861e430-d375-4228-af1e-a6e35b85d514)
https://react.dev/errors/423?invariant=423

**Comment by pionxzh** [comment]
Don't worry about the react error.

What's your browser and the version?

**Comment by pionxzh** [comment]
Also, take a screenshot of the contents after clicking the link

![Screenshot_2024-09-14-20-27-40-93_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/026986f2-f34b-4e59-926e-684ae097f733)

**Comment by 14790897** [comment]
I wrote the wrong code in the script, your code works correctly now.
