### ISSUE TITLE
Conversations begin with Unsupported Content on Plus Account

### ISSUE THREAD

**Issue by moonmd** [pionxzh/chatgpt-exporter#269]
I am getting an extra entry of [Unsupported Content] at the top of my conversations. (Plus Account only)

``` title: Markdown begins with
# Trig Integrals Simplified

#### You:
[Unsupported Content]

#### You:
What is the trig integral for the squares of sin and cos?

#### ChatGPT:
The integrals of the squares of sine and cosine...
```
I tracked down the cause to this 
`content.content_type = user_editable_context`

Tested in Linux MS Edge & Firefox. [Tampermonkey github install](https://raw.githubusercontent.com/pionxzh/chatgpt-exporter/master/dist/chatgpt.user.js)

**Comment by moonmd** [comment]
If this is an issue other people are having, I have performed initial tests on this commit:
https://github.com/moonmd/chatgpt-exporter/commit/ad30280ccfb05a765396eb9dbadf9f7252fa5f28

**Comment by pionxzh** [comment]
Can confirm this bug was caused by "Custom instructions"
