### ISSUE TITLE
Recommended that the exporter button to the top of the question bar.

### ISSUE THREAD

**Issue by TheresaCBE** [pionxzh/chatgpt-exporter#28]
#Request
![图像 1](https://user-images.githubusercontent.com/44676563/209073302-008897b5-c7fc-43a0-92cf-1d78007e8ebb.png)

So that the objects in the page will not disappear due to the shrinkage of the page.

**Comment by pionxzh** [comment]
I will think about it. Thanks for the suggestion.

**Comment by pionxzh** [comment]
The new UI has been shipped in [v1.5.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.5.0). Take a look and let me know what you think 😄

**Comment by pionxzh** [comment]
I will close this as won't implement. The "Regenerate" button is not stable enough. It won't be displayed in all the scenarios.
