### ISSUE TITLE
Didn't work in firefox

### ISSUE THREAD

**Issue by Kreijstal** [pionxzh/chatgpt-exporter#3]
Tried:
-Tampermonkey
-Violentmonkey

Tried to debug it, but the plugin is super huge, and it tries to log in to some thing, not sure, I gave up.

**Comment by gloin01** [comment]
I tried it in both Firefox and Google Chrome and both doesn't seem to work with Tampermonkey.

**Comment by pionxzh** [comment]
fixed in [v1.1.1](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.1.1)
