### ISSUE TITLE
Discussion: UI Improvement

### ISSUE THREAD

**Issue by pionxzh** [pionxzh/chatgpt-exporter#31]
After adding markdown support #29 in [v1.4.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.4.0), we have 4 items in the sidebar which occupied a lot of space.
I'm thinking about improving the UI.

![image](https://user-images.githubusercontent.com/9910706/209852250-5ab8ff44-02e7-4647-9668-a46f46dd2a70.png)

1. The first idea that came to my mind was to create a popover on hover which would show all the export formats.
2. The second one is from #28 which adds the button beside "Regenerate". But we still need solutions like the first one to prevent scattering 4 long buttons.

And I also want to shorten the text on buttons 😄 
Feel free to share your idea ✨

**Comment by Athari** [comment]
I've just restyled the page to make all buttons compact. I don't need huge paddings and margins when on desktop.

![image](https://user-images.githubusercontent.com/1715107/211188620-84597e39-d39c-4379-a1d4-4568120049a0.png)

Of course, this solution isn't for everyone. Popover on hover would probably make the most sense for majority of users.

**Comment by pionxzh** [comment]
This is what the updated dropdown looks like.

![image](https://user-images.githubusercontent.com/9910706/211209087-13e81f7d-8565-4b69-b118-ba08cfb2e830.png)

**Comment by Notarin** [comment]
@pionxzh just saw this in the new build, I really like this update, thank you as usual!
