### ISSUE TITLE
Support for table parsing

### ISSUE THREAD

**Issue by ameen-roayan** [pionxzh/chatgpt-exporter#32]
This script is really Amazing ! 

Just having a minor issue where the format of a table would not carry over to the HTML, images for comparison:

![image](https://user-images.githubusercontent.com/92278134/210490427-1398f949-220e-4220-aac1-a3b5d9aa0b9b.png)

![image](https://user-images.githubusercontent.com/92278134/210490463-4fc78f4e-0fe5-4e2f-bd56-14f203282a87.png)

Hopefully not a hassle to fix.

Thanks !

**Comment by pionxzh** [comment]
I don't even know ChatGPT can output a table 🙈
Thanks for letting me know.

**Comment by pionxzh** [comment]
This has been released in [v1.5.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.5.0). Let me know if this is still present.
![image](https://user-images.githubusercontent.com/9910706/211209025-2da0fbfc-b705-4461-b9e8-0bbb2c153d33.png)

![image](https://user-images.githubusercontent.com/9910706/211209057-3545667b-25b8-44e1-ad0b-5b4d9057a47c.png)
