### ISSUE TITLE
Chat names can be used as a titles and file names for exported chats

### ISSUE THREAD

**Issue by Athari** [pionxzh/chatgpt-exporter#35]
Now that ChatGPT supports multiple chats, chat names can be used as file names (instead of "chatgpt+date") and as titles with header tag within the file. Let's say the chat in named "Patching KDE2 on FreeBSD", then the markdown file can be exported with this text:

```markdown
# Patching KDE2 on FreeBSD

You:
How does one patch KDE2 under FreeBSD?

ChatGPT:
To patch KDE2 under FreeBSD, you will need to follow these steps:
(...)
```

and the file itself can be named `Patching_KDE2_on_FreeBSD.md` (I'd say the current date is unnecessary because it's stored in the metadata within the file system, but it's up to you).

The same with copied text and HTML exports.

**Comment by pionxzh** [comment]
Good point. How about `ChatGPT-{title}.{ext}` ?
Not sure if we should keep the timestamp? :/

**Comment by Athari** [comment]
`ChatGPT-{title}.{ext}` sounds good.

Not sure about the dash though. ChatGPT tends to generate natural titles with spaces in them, so the dash separator would look alien. Spaces in the title can be replaced with dashes or underscores, but maybe it's a better idea to let the browser decide how to adjust the name to the rules of the user's file system.

The timestamp would make sense if it reflected the time the chat was generated. If I understand correctly, currently the timestamp is just the time of exporting/copying. And that already exists as the time of file creation/modification within the file system.  I'd say, if the time the messages were actually posted/generated isn't present anywhere on the webpage, then there's little value in having a timestamp in the file or file name, but that's just me.

**Comment by pionxzh** [comment]
Spaces in the title will be replaced with `_` to prevent the troublesome on different platforms.
Example: `chatgpt-List_Solar_System_Planets.md`

Will this dash still look like an alien? Dash is the separator of chatgpt and title.
And thanks for the input about timestamp. I will remove it.

**Comment by Athari** [comment]
Are spaces in filenames actually troublesome anywhere except for bad shell scripts? 😁 Underscores would work, but there's no guarantee ChatGPT won't put some special characters into the chat name, so fixing the name would be the browser's job anyway.

Also, fun fact: `https://chat.openai.com/backend-api/conversations?offset=0&limit=20` does contain chat creation time, it just isn't displayed in the UI. Not sure how useful this is as the query requires a token. I don't know whether intercepting this query is possible and worth the hassle, but the data is there. `https://chat.openai.com/backend-api/conversation/CHATGUID` contains timestamps of every message too, among other things.

**Comment by pionxzh** [comment]
Actually I'm not sure how troublesome it gonna be. I will sanitize the title to prevent special characters.

It's possible to send out the request as a userscript. But it might not be worth it to retrieve this kind of information.
Anyway, thanks for the information.
