### ISSUE TITLE
Support for Heading, Bold and Italic

### ISSUE THREAD

**Issue by huhuhang** [pionxzh/chatgpt-exporter#37]
# Prompts

```text
Please output a markdown text
```

![CleanShot 2023-01-13 at 09 58 03](https://user-images.githubusercontent.com/5147530/212219483-0424e156-851a-4bcb-a91f-535eb531b992.png)

# Outputs

`#  is missing`

![CleanShot 2023-01-13 at 09 58 37](https://user-images.githubusercontent.com/5147530/212219581-4ce67063-a062-4852-8867-a4163a239220.png)

There are also minor issues with bold and italic. 😂

Thanks for providing such a great tool!

**Comment by pionxzh** [comment]
Thanks. I don't know ChatGPT will output so many different formats 😆

**Comment by pionxzh** [comment]
I have rewritten the parsing process to accept (most of?) different formats.
Let me know if you see any new unsupported formats.

**Comment by huhuhang** [comment]
> I have rewritten the parsing process to accept (most of?) different formats. Let me know if you see any new unsupported formats.

Thank U. 😄
