### ISSUE TITLE
Request: Feature to download ALL chats

### ISSUE THREAD

**Issue by platinorum** [pionxzh/chatgpt-exporter#39]
First of all, thank you for the great user script, it is very helpful.

I have a feature request: could you implement an **option to export all available chats**?
I just installed the script and I want to export/save all my existing chats, but I have a lot of them, so it would take a long time to export each file individually. So I thought an option to download all the previous chats and maybe pack them into a zip file would be useful.

**Comment by pionxzh** [comment]
After not being able to see my chat history... I will make this a top priority 😆
