### ISSUE TITLE
Filename input is unreadable (black on black)

### ISSUE THREAD

**Issue by dserodio** [pionxzh/chatgpt-exporter#42]
The input field for choosing the filename is black text on black background

![image](https://user-images.githubusercontent.com/233589/216714232-7bb294da-189e-4f69-9a83-fcfb66200337.png)

**Comment by pionxzh** [comment]
My bad. I forgot to release #41.

**Comment by pionxzh** [comment]
Fixed in release [v1.7.1](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.7.1)

**Comment by dserodio** [comment]
Thanks!
