### ISSUE TITLE
Export is missing some backticks for code

### ISSUE THREAD

**Issue by dserodio** [pionxzh/chatgpt-exporter#43]
When ChatGPT generates inline code, it surrounds it with backticks, Markdown-style. But some of them (not all) are lost when exported to HTML or Markdown. It would be perfect if the backticks are kept, specially for Markdown. I think this example will make it clear:

In ChatGPT webpage:

![image](https://user-images.githubusercontent.com/233589/217553855-380936bf-cbd1-4383-84cf-07a236357f2b.png)
---
Export to HTML using ChatGPT Exporter:

![Pasted_Image_08_02_23_11_13_AM](https://user-images.githubusercontent.com/233589/217554222-f13f2374-bd2c-4c61-9131-019fa5deb7dd.png)

And thanks a lot for making ChatGPT Exporter, it's really useful!

**Comment by pionxzh** [comment]
You should be able to see the correct format in [1.7.2](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.7.2)
![image](https://user-images.githubusercontent.com/9910706/218153963-655f0c2d-385c-489b-b220-68e8acb6c73d.png)
