### ISSUE TITLE
Mobile version support

### ISSUE THREAD

**Issue by kyoyacchi** [pionxzh/chatgpt-exporter#45]
I'd like to use it on mobile version too , but it looks like this;
![Screenshot_20230214-190220](https://user-images.githubusercontent.com/63583961/218791790-ca17110e-7d43-40b7-86e0-50977d7fd731.jpg)
I can barely click them and can't see texts.

Can you improve it for mobile version? I'm using Kiwi Browser, (Violentmonkey ext.)

**Comment by pionxzh** [comment]
Oh I didn't expect people can use a userscript on their phone. 😄 
Sure, let me see how to improve the behavior here.

**Comment by pionxzh** [comment]
This is what it will look like in the next version.
But I couldn't test this on an actual phone. 🙏 

![chrome_2ww8zpEsHd](https://user-images.githubusercontent.com/9910706/219647541-9f9e1e42-95a4-4491-9958-2319bb8d0c85.gif)

**Comment by pionxzh** [comment]
Please note that mobile devices who are not supporting [`:has()`](https://caniuse.com/css-has) selector will not being able to use this feature.
