### ISSUE TITLE
Request: Make title of page, the title of the chat from ChatGPT

### ISSUE THREAD

**Issue by bryanschmidty** [pionxzh/chatgpt-exporter#46]
Currently, the title of the exported HTML page is "ChatGPT Conversation". It would be great if, instead, it was set to the title of the chat within ChatGPT that is on the left sidebar navigation.

**Comment by pionxzh** [comment]
Good idea. This is more like part of #35  being forgotten by me. 😝

**Comment by bryanschmidty** [comment]
oh! I just now noticed the ability to change the name in the export. I can just set it to `{title}`. Perhaps this issue can be closed.

**Comment by bryanschmidty** [comment]
well now I'm confusing myself. That is the filename, not the title. Ignore that last comment 😛
