### ISSUE TITLE
When exporting Markdown with code blocks, ^M line endings are intermittent

### ISSUE THREAD

**Issue by joeytwiddle** [pionxzh/chatgpt-exporter#49]
I guess this is ChatGPT not really caring about line endings. I ended up with a document which was neither Unix `\n` or Windows `\r\n`, but a mixture of the two.

(In VIM on Linux, this manifests as some lines having `^M` on the end, and some not.)

I would suggest chatgpt-exporter do a final pass over the document, to ensure every line ends in `\r\n`, to produce a DOS/Windows-style file which will also work fine on *nix.

My issue was with Markdown files. I don't know if HTML and TXT modes have the same issue, but I guess the same approach for them wouldn't hurt.

**Comment by pionxzh** [comment]
So `\r\n` will be the best choice for cross-platform compatibility? Let me check check.

**Comment by joeytwiddle** [comment]
I did think `\r\n` would be the most compatible.

But `\n` should be good enough for now, until someone raises an issue.

I think Windows Notepad now handles `\n` well. But astonishingly, `bash` under WSL does not!

**Comment by pionxzh** [comment]
tbh I don't have enough knowledge and experience about line ending. So `\n` is actually what ChatGPT tells me 🤣
