### ISSUE TITLE
Windows Firefox: Button, but no menu

### ISSUE THREAD

**Issue by holgerpieta** [pionxzh/chatgpt-exporter#51]
On Windows Firefox 110.0 with Tampermonkey 4.18.1 and chatgpt-exporter 1.8.0 the button is correctly added to the sidebar, but when I mouse over it, no menu appears, just a little triangle pointing left. There is nothing to click that would bring up the menu.
I've tried disabling all other extensions, but that didn't help either.
Anything I can do to help debug that?

**Comment by pionxzh** [comment]
I'm a plus user too. Let me check what happened on Firefox.

**Comment by ikidd** [comment]
Downgrading works, FF 109.0.1 on Manjaro

**Comment by pionxzh** [comment]
The root cause of this is that I introduced [:has()](https://caniuse.com/css-has) selector for mobile version support #45. And I forgot to provide a fallback for unsupported devices.
