### ISSUE TITLE
user pfp was cut off in screenshot mode

### ISSUE THREAD

**Issue by kyoyacchi** [pionxzh/chatgpt-exporter#53]
When i export a conversation, it zooms in the picture and cuts it.
Like this.
![ChatGPT-2023-02-21T16-54-40](https://user-images.githubusercontent.com/63583961/220410050-4133da09-4554-49b9-a321-1ac2de326b8e.png)

And this is normal pfp
![Screenshot_20230221-195811](https://user-images.githubusercontent.com/63583961/220410631-488ebae1-05a4-4d4e-81d6-982f87e56dbb.jpg)

**Comment by pionxzh** [comment]
I couldn't reproduce the issue. Not sure what exactly happened.

This is the screenshot I get on both desktop/mobile.
![image](https://user-images.githubusercontent.com/9910706/221415839-6bb3ea28-eb40-482c-9f96-5e25017f6a6f.png)
![image](https://user-images.githubusercontent.com/9910706/221415868-685ecf58-5303-4897-a229-fd80239e982a.png)

**Comment by kyoyacchi** [comment]
> I couldn't reproduce the issue. Not sure what exactly happened.
> 
> This is the screenshot I get on both desktop/mobile. ![image](https://user-images.githubusercontent.com/9910706/221415839-6bb3ea28-eb40-482c-9f96-5e25017f6a6f.png) ![image](https://user-images.githubusercontent.com/9910706/221415868-685ecf58-5303-4897-a229-fd80239e982a.png)

Can you try with this one?
https://imgur.com/a/NSNhNz1

It's still same even when i switch to desktop mode..
I tried with Lemur Browser, it's same.
Desktop mode
![ChatGPT-2023-02-26T18-36-21](https://user-images.githubusercontent.com/63583961/221429948-0709ec7b-a42b-4cf2-8f84-499595f2f6bb.png)
Mobile
![ChatGPT-2023-02-26T18-38-31](https://user-images.githubusercontent.com/63583961/221429966-b61c8309-c20f-4c25-bd80-8895d05d6c6a.png)

**Comment by kyoyacchi** [comment]
I guess the image causes this ._.

**Comment by pionxzh** [comment]
@kyoyacchi May I know your device and OS version?

**Comment by pionxzh** [comment]
I guess it might be related to https://github.com/niklasvh/html2canvas/issues/2795

**Comment by pionxzh** [comment]
I just released [v1.9.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.9.0). Let me know if this version can fix the issue.

**Comment by kyoyacchi** [comment]
> I just released [v1.9.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v1.9.0). Let me know if this version can fix the issue.

Still same. It didn't even show the pfp at for once

**Comment by pionxzh** [comment]
I see 😢 

> It didn't even show the pfp at for once

The pfp is not that stable in screenshot mode

**Comment by pionxzh** [comment]
[v2.0.0](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.0.0) use another strategy to render the pfp.
Could you help to verify if this gets fixed?

**Comment by pionxzh** [comment]
so weird :/

**Comment by pionxzh** [comment]
I updated my pfp and this issue should be fixed.

**Comment by kyoyacchi** [comment]
> I updated my pfp and this issue should be fixed.

Yes it seems so.
