### ISSUE TITLE
Misleading meta information (mostly just layout and wording)

### ISSUE THREAD

**Issue by Wolf-SO** [pionxzh/chatgpt-exporter#55]
In the heading of the HTML exports (I didn't check other options), the two lines 

> Time: 2023-02-26T12:29:19.649Z
Generated by [ChatGPT Exporter](https://github.com/pionxzh/chatgpt-exporter)

... can lead to confusion, because 
- the timestamp indicates the export time
- the word *generated* could be misunderstood, it's only the HTML output that was generated.

What about putting both information it in one line with slight modifications like this:

> Exported by  [ChatGPT Exporter](https://github.com/pionxzh/chatgpt-exporter) at 2023-02-26T12:29:19.649Z

**Comment by pionxzh** [comment]
Sounds good. 👍
