### ISSUE TITLE
The bottom part of Screenshot will be cut on Firefox

### ISSUE THREAD

**Issue by pionxzh** [pionxzh/chatgpt-exporter#6]

**Comment by hell0github** [comment]
This also happens for Safari and Chrome. I am using Macbook Air M1, MacOS 13.0.1. I have tested the scripts and confirmed the issue for both of these two browsers.

**Comment by pionxzh** [comment]
> This also happens for Safari and Chrome. I am using Macbook Air M1, MacOS 13.0.1. I have tested the scripts and confirmed the issue for both of these two browsers.

Thanks for the reporting

**Comment by pionxzh** [comment]
I am currently on vacation. I was wondering if anyone could help by submitting a pull request to fix this issue. Thank you!

It should be something related to the `html2canvas`
https://github.com/pionxzh/chatgpt-exporter/blob/master/packages/userscript/src/main.ts#L132-L137

**Comment by pionxzh** [comment]
It seems like this issue no longer exists in the latest version. I'm closing this as resolved. Please inform me if you encounter this issue again.
