### ISSUE TITLE
Missing some text in list item when export

### ISSUE THREAD

**Issue by snowman** [pionxzh/chatgpt-exporter#60]
![image](https://user-images.githubusercontent.com/16096559/221744871-dfcca045-6324-4a80-9798-da9eb7170e5f.png)

Text: (the list item only `code` get extracted)
<pre>
You:
Show me what this function does in step-by-step form:

def say(text):
  print('...')
  print(text)

ChatGPT:
Sure, here's a step-by-step breakdown of what this function `say(text)` does:

1. say
text
2. say
text
...
text
3. say

So, if you were to call the `say` function like this:

```perl
say("Hello, World!")
```

The output would be:

```python-repl
...
Hello, World!
```

I hope that helps!
</pre>

**Comment by snowman** [comment]
I don't know whether is now supported nested list item, hence mention it here also

![image](https://user-images.githubusercontent.com/16096559/221746079-9831cd56-519f-4568-96ef-308c9998709b.png)

**Comment by pionxzh** [comment]
Nesting might not work as intended. I will work on fixing it.

**Comment by snowman** [comment]
![image](https://user-images.githubusercontent.com/16096559/224308289-06e32752-3d6d-4e85-882c-1aa40b026249.png)

These blue text still *NOT* exported when in list item.

**Comment by pionxzh** [comment]
@snowman did you test this on [v2.1.2](https://github.com/pionxzh/chatgpt-exporter/releases/tag/userscript-v2.1.2)?

**Comment by snowman** [comment]
Thanks, I upgrade to `v2.1.2`, now it works ~
