### ISSUE TITLE
Put additional information into front-matter in Markdown export

### ISSUE THREAD

**Issue by dumojun101** [pionxzh/chatgpt-exporter#61]
类似这种：

```markdown
---
created: 20230223-205207-3140 (UTC +08:00)
tags: []
source: https://chat.openai.com/chat/1df14491-32e4-4aa3-9786-42cad28105e7
author: Rick Wayne
原文字数: 1888
收藏者： 进步哥
内容方向： 
---
```

**Comment by pionxzh** [comment]
Good idea. I think #54 's information can also be expressed in this front-matter format.

**Comment by dumojun101** [comment]
类似：


 function getNowTime(){
          var now = new Date();
          var year = now.getFullYear();
          var month = now.getMonth() + 1;
          var date = now.getDate();
          var hours = now.getHours();
          var minutes = now.getMinutes();
          var seconds = now.getSeconds();
          hours = hours < 10 ? '0' + hours : hours;
          minutes = minutes < 10 ? '0' + minutes : minutes;
          seconds = seconds < 10 ? '0' + seconds : seconds;
          if (month < 10){
              month = "0" + month;}
          if (date < 10){
              date = "0" + date;}


          var dateString = year + "-" + month + "-" + date + " " + hours + ":" + minutes + ":" + seconds;
          var dateStringOne = year + month + date + "-" + hours+ minutes + seconds;

          return dateString;
      }

   function getInfo(){
          let allContent ="";
          try{
              const username = document.querySelector(".username").firstChild.textContent.trim();
              const pudate_text = document.querySelector(".pudate-text").firstChild.textContent.trim();
              const views = document.querySelector("span.view.item").getAttribute("title");
              let pUrl = window.location.href;
              let match = pUrl.match(/(https\:\/\/www.bilibili.com\/video\/)(BV|av)[a-zA-Z0-9]+(?=[\/\?])?/g);
              pUrl = match ? match[0] : pUrl;
              allContent = "---\ntags: bilibili_note\nurl: "+pUrl+"\nup: "+username+"\nup_date: "+pudate_text+"\ndown_time: "+getNowTime()+"\nviews: "+views+"\n收藏者：进步哥"+"\n---\n\n# 谢谢您！\n\n";
          }catch(e){
              let pUrl = window.location.href;
              let match = pUrl.match(/(https\:\/\/www.bilibili.com\/video\/)(BV|av)[a-zA-Z0-9]+(?=[\/\?])?/g);
              pUrl = match ? match[0] : pUrl;
              allContent = "---\ntags: bilibili_note\nurl: "+pUrl+"\ndown_time: "+getNowTime()+"\n---\n\n";
          }
      return allContent;
      }

**Comment by pionxzh** [comment]
This feature will be designed to be like:
1. Both `Markdown` and `HTML` will support additional metadata (title, date, time, model...)
2. Setting dialog will have a section to configure the content and format of the meta
3. Allow users to customize their date-time format
