### ISSUE TITLE
Just export/copy last response from ChatGPT

### ISSUE THREAD

**Issue by ALANDVO** [pionxzh/chatgpt-exporter#63]
Is there anyway we can have an option to Just export/copy last response from ChatGPT?

**Comment by pionxzh** [comment]
Hmm I think we can put it around the 👍 👎  buttons. This will be useful for copying long response from ChatGPT.
![image](https://user-images.githubusercontent.com/9910706/222316440-ff9a45cc-1e4d-4153-8010-0b18721e0dce.png)

**Comment by ALANDVO** [comment]
That would be awesome!!!!

**Comment by pionxzh** [comment]
Large screen(right side)
![image](https://user-images.githubusercontent.com/9910706/226123165-c2b18471-12e2-49ac-8416-55d619a37f0e.png)
Medium and Mobile
![image](https://user-images.githubusercontent.com/9910706/226123202-afd50899-0ea7-4773-994d-a3d1ad20d614.png)

**Comment by kyoyacchi** [comment]
> Large screen(put it to the next line so that it won't shrink the width of text content) ![image](https://user-images.githubusercontent.com/9910706/226123165-c2b18471-12e2-49ac-8416-55d619a37f0e.png) Medium and Mobile ![image](https://user-images.githubusercontent.com/9910706/226123202-afd50899-0ea7-4773-994d-a3d1ad20d614.png)

Looks complicated with the code blocks (in mobile)
![Screenshot_20230319-154053](https://user-images.githubusercontent.com/63583961/226175834-e7305506-2718-4fad-b096-a3f62435e2b3.jpg)
