### ISSUE TITLE
line-break is not being respected in HTML export.

### ISSUE THREAD

**Issue by Wolf-SO** [pionxzh/chatgpt-exporter#65]
This is what I see in the original ChatGPT web interface (after reloading an old chat):

![grafik](https://user-images.githubusercontent.com/29630128/222956685-db440e1c-3b9c-4bef-ac93-5c389f45089d.png)

And this is what I see in the export of chatgpt-exporter version 1.9.1

![grafik](https://user-images.githubusercontent.com/29630128/222955909-5393ee67-8b7d-4d45-822c-e40383b6f903.png)

The HTML node for the poem (via *copy outer HTML* in *Developer Tools*) looks exactly the same in both cases:

```html
<p>A machine tried to pass the test,
But failed to impress with its best,
Its answers were too quick,
Its humor too slick,
The machine's true nature laid to rest.</p>
```

I tried to find the CSS responsible for rendering `\n` as line breaks, but I couldn't.

**Comment by pionxzh** [comment]
Could you help to take a screenshot of the poem's original HTML structure?

**Comment by Wolf-SO** [comment]
This is exactly what I added at the end. It's indistinguishable from that in the export.

**Comment by pionxzh** [comment]
the css you are trying to find should be `white-space: pre-line;`

**Comment by Wolf-SO** [comment]
Thanks, I'll try it in a moment.

**Comment by pionxzh** [comment]
Hmm I just simulate the content and it looks like we will need this CSS style, or transform the `\n` into `<br />` properly.

I think this will be fixed in v2 (#64) automatically.

**Comment by Wolf-SO** [comment]
I tried and this indeed fixed the appearance, so I think we should better use this CSS (and keep the actual content as it is).

**Comment by pionxzh** [comment]
I just checked how ChatGPT handles this. We will follow their ways with `white-space: pre-wrap;`.

**Comment by Wolf-SO** [comment]
I tried to figure out the difference between `pre-line` (your first hint) `pre-wrap` (as can be seen in the chat GUI). And it seems that the results can slightly differ it the text width differs between original view and export, which is currently the case (but I do not know how stable it will be in the original). Should I investigate further and add another issue for that?

**Comment by pionxzh** [comment]
I think I know the reason... I just applied some CSS rules to make it look better.
See https://github.com/pionxzh/chatgpt-exporter/pull/64/commits/7bc47a325e51be60fa9d48c2d626d3286f31d42e
