### ISSUE TITLE
WebPage export fails silently on CORS error

### ISSUE THREAD

**Issue by absurd** [pionxzh/chatgpt-exporter#73]
In v 2.1.2 running via Tampermonkey on Firefox 110.0.1, WebPage export silently fails. In the console the following error is present:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s.gravatar.com/avatar/0c181e86176a1f93abd43da1d429bc55?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fop.png. (Reason: CORS request did not succeed). Status code: (null).
```

Commenting out the contents of the `getUserAvatar` function [here](https://github.com/pionxzh/chatgpt-exporter/blob/1c35eee15fbe2135f7cf317d45ec5972190fdad9/packages/userscript/src/page.ts#L57) such that it returns `defaultAvatar` without attempting [loadImage](https://github.com/pionxzh/chatgpt-exporter/blob/1c35eee15fbe2135f7cf317d45ec5972190fdad9/packages/userscript/src/utils/dom.ts#L16) resolves the problem:

```javascript
async function getUserAvatar() {
    /*const {
      picture
    } = getUserProfile();
    if (picture)
      return getBase64FromImageUrl(picture);*/
    return defaultAvatar;
  }
```

Previously WebPage export worked without modifying the script.

**Comment by pionxzh** [comment]
> In v 2.1.2 running via Tampermonkey on Firefox 110.0.1, WebPage export silently fails. In the console the following error is present:
> 
> ```
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://s.gravatar.com/avatar/0c181e86176a1f93abd43da1d429bc55?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fop.png. (Reason: CORS request did not succeed). Status code: (null).
> ```
> 
> Commenting out the contents of the `getUserAvatar` function [here](https://github.com/pionxzh/chatgpt-exporter/blob/1c35eee15fbe2135f7cf317d45ec5972190fdad9/packages/userscript/src/page.ts#L57) such that it returns `defaultAvatar` without attempting [loadImage](https://github.com/pionxzh/chatgpt-exporter/blob/1c35eee15fbe2135f7cf317d45ec5972190fdad9/packages/userscript/src/utils/dom.ts#L16) resolves the problem:
> 
> ```js
> async function getUserAvatar() {
>     /*const {
>       picture
>     } = getUserProfile();
>     if (picture)
>       return getBase64FromImageUrl(picture);*/
>     return defaultAvatar;
>   }
> ```
> 
> Previously WebPage export worked without modifying the script.

I see. Firefox might have stricter rules on this. I will try to use the old way as a fallback.
