### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by mbprotheweb** [pionxzh/chatgpt-exporter#75]
Stopped working after new release
Please advise

![Screenshot 2023-03-15 162234](https://user-images.githubusercontent.com/100542453/225433362-1d0b0933-7b81-4486-975a-ab6365495058.png)

**Comment by gileneusz** [comment]
I have the same error on Edge.

**Comment by pionxzh** [comment]
Sorry I didn't notice that there are some difference between dev build and prod build
