### ISSUE TITLE
Screenshot font issue for user messages

### ISSUE THREAD

**Issue by coranholmes** [pionxzh/chatgpt-exporter#78]
Hi! Thank you for the great work! I am using Firefox 111.0 (64-bit) and MacOS Ventura 13.2.1.

I find when I export the dialog into screenshots, the font for user messages look wired, the spaces seem not properly display. 
<img width="525" alt="tt" src="https://user-images.githubusercontent.com/2607616/225529501-8dbc0750-4422-4ac7-9280-d260499c9266.png">

大佬求帮帮忙ヾ(✿ﾟ▽ﾟ)ノ

**Comment by pionxzh** [comment]
Looks like this only happened on Firefox. I will check on my PC later.

**Comment by pionxzh** [comment]
Hmm it works on my firefox...
Browser: Firefox 111.0 (64-bit)
OS: Windows 11

wait let me check my Mac

**Comment by coranholmes** [comment]
I am using plugin Violentmonkey 2.14.0 for firefox, is this relevant?

**Comment by pionxzh** [comment]
Violentmonkey should be okay.
I have reproduced this on MacOS 13.2.
It's either a bug from `html2canvas` or Firefox on MacOS.
I will try to find some workaround.

**Comment by pionxzh** [comment]
https://github.com/niklasvh/html2canvas/issues/3037

**Comment by pionxzh** [comment]
I finally found a workaround for this. @coranholmes can you help to confirm?

~~火狐你坏事做尽~~ 💢

**Comment by coranholmes** [comment]
I cleared the cache and now it worked fine! Thank you!
