### ISSUE TITLE
Export to webpage does not work

### ISSUE THREAD

**Issue by coranholmes** [pionxzh/chatgpt-exporter#79]
Hi! Thank you for the great work! Export to webpage seem do not work now. This is also mentioned by other uses [here](https://greasyfork.org/zh-CN/scripts/456055-chatgpt-exporter/feedback). I am using Firefox 111.0 (64-bit), not sure whether this is related to browser~

**Comment by pionxzh** [comment]
could you share the error message in console? it's working on my firefox + macos

**Comment by coranholmes** [comment]
I have updated to the latest version and it works now. Thanks!
