### ISSUE TITLE
Missing user profile picture in image export

### ISSUE THREAD

**Issue by emilesilvis** [pionxzh/chatgpt-exporter#80]
Version 2.2.1.

![ChatGPT-AI_stance_analyzer](https://user-images.githubusercontent.com/557338/225553585-316ca935-5e64-4654-af9f-f42db442aada.png)

**Comment by emilesilvis** [comment]
Seems to be a once-off niggly.

**Comment by pionxzh** [comment]
ye it's not that stable. And it would be hard to fix this on our side.
