### ISSUE TITLE
Delete conversations when saved

### ISSUE THREAD

**Issue by ifuchs** [pionxzh/chatgpt-exporter#85]
Any chance that the extension could have an option to delete any chats it downloads and saves?

**Comment by pionxzh** [comment]
Technically, it's doable. But I would choose to let users do this risky action by themself.

**Comment by ifuchs** [comment]
I was suggesting that it be an option,  not that it be the default.

**Comment by pionxzh** [comment]
Deleting a chat after clicking `Markdown` is still really weird. I know it's tedious to delete a lot of chat, but this is not what I think the exporter should do.

**Comment by ifuchs** [comment]
Having a delete button after archiving is not unusual. Perhaps there could be another greasemonkey script that did this…list all the chats and have you check which ones to delete.

**Comment by pionxzh** [comment]
So what you proposed is to add a delete/clean button in the dialog of `Export All`?

**Comment by ifuchs** [comment]
What I was envisioning is a button that if checked would delete the chats that you have downloaded. If that is all of them, then yes, it would delete all otherwise it would just delete the ones that you had checked to export.

**Comment by ifuchs** [comment]
It could also be a function separate from the download altogether so that the usesr could confirm that the download worked before deleting the chats.

**Comment by pionxzh** [comment]
I will think about it

**Comment by pionxzh** [comment]
I have added the feature to select and delete multiple chats.
![image](https://user-images.githubusercontent.com/9910706/230092633-4c2663aa-d6a4-41eb-a2b4-8e36eeb7e071.png)

I will release tomorrow.
