### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by kyoyacchi** [pionxzh/chatgpt-exporter#91]
Can you add multilanguage support for texts? Such as Turkish , Japanese etc... I can translate Turkish language if you want.

**Comment by pionxzh** [comment]
You mean i18n on UI layout?

**Comment by kyoyacchi** [comment]
> You mean i18n on UI layout?

yes. sorry for being unclear

**Comment by pionxzh** [comment]
Ok. Let me do some experiments and get back to you.

**Comment by pionxzh** [comment]
@kyoyacchi I have implemented the i18n setup. Feel free to contribute Turkish~
I can kind of understand Japanese, so I just let ChatGPT generate one for me. 😆

**Comment by kyoyacchi** [comment]
> @kyoyacchi I have implemented the i18n setup. Feel free to contribute Turkish~ I can kind of understand Japanese, so I just let ChatGPT generate one for me. 😆

Thanks 🥳! (*Ellerine sağlık* _:D_) I did open a PR after seeing your comment right away #128, I know a little bit Japanese too even tho just romaji.
