### ISSUE TITLE
I often use https://freegpt.one/.Can this script be compatible with this mirror station?

### ISSUE THREAD

**Issue by niuble6** [pionxzh/chatgpt-exporter#98]
I often use https://freegpt.one/

Can this script be compatible with this mirror station?

**Comment by pionxzh** [comment]
I just checked the site. But I don't know whether they also offered the same API.
Supporting mirror site is not on the plan.

My suggestion is:
1. Clone this repo and update the base URL from openai to this site and see how things are going.
2. Or use the V1 version of this script which is based on the page HTML. This should be more compatible with other mirror sites.
